# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2DownloadSummary")

model_instance <- V2DownloadSummary$new()

test_that("record_count", {
  # tests for the property `record_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`record_count`, "EXPECTED_RESULT")
})

test_that("assembly_count", {
  # tests for the property `assembly_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_count`, "EXPECTED_RESULT")
})

test_that("resource_updated_on", {
  # tests for the property `resource_updated_on` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`resource_updated_on`, "EXPECTED_RESULT")
})

test_that("hydrated", {
  # tests for the property `hydrated` (V2DownloadSummaryHydrated)

  # uncomment below to test the property
  #expect_equal(model.instance$`hydrated`, "EXPECTED_RESULT")
})

test_that("dehydrated", {
  # tests for the property `dehydrated` (V2DownloadSummaryDehydrated)

  # uncomment below to test the property
  #expect_equal(model.instance$`dehydrated`, "EXPECTED_RESULT")
})

test_that("errors", {
  # tests for the property `errors` (array[V2reportsError])

  # uncomment below to test the property
  #expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})

test_that("messages", {
  # tests for the property `messages` (array[V2reportsMessage])

  # uncomment below to test the property
  #expect_equal(model.instance$`messages`, "EXPECTED_RESULT")
})

test_that("available_files", {
  # tests for the property `available_files` (V2DownloadSummaryAvailableFiles)

  # uncomment below to test the property
  #expect_equal(model.instance$`available_files`, "EXPECTED_RESULT")
})
