# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2OrganelleDownloadRequest")

model_instance <- V2OrganelleDownloadRequest$new()

test_that("accessions", {
  # tests for the property `accessions` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`accessions`, "EXPECTED_RESULT")
})

test_that("exclude_sequence", {
  # tests for the property `exclude_sequence` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`exclude_sequence`, "EXPECTED_RESULT")
})

test_that("include_annotation_type", {
  # tests for the property `include_annotation_type` (array[V2AnnotationForOrganelleType])

  # uncomment below to test the property
  #expect_equal(model.instance$`include_annotation_type`, "EXPECTED_RESULT")
})
