# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsTranscript")

model_instance <- V2reportsTranscript$new()

test_that("accession_version", {
  # tests for the property `accession_version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession_version`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("length", {
  # tests for the property `length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`length`, "EXPECTED_RESULT")
})

test_that("cds", {
  # tests for the property `cds` (V2reportsSeqRangeSet)

  # uncomment below to test the property
  #expect_equal(model.instance$`cds`, "EXPECTED_RESULT")
})

test_that("genomic_locations", {
  # tests for the property `genomic_locations` (array[V2reportsGenomicLocation])

  # uncomment below to test the property
  #expect_equal(model.instance$`genomic_locations`, "EXPECTED_RESULT")
})

test_that("ensembl_transcript", {
  # tests for the property `ensembl_transcript` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ensembl_transcript`, "EXPECTED_RESULT")
})

test_that("protein", {
  # tests for the property `protein` (V2reportsProtein)

  # uncomment below to test the property
  #expect_equal(model.instance$`protein`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (V2reportsTranscriptTranscriptType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("select_category", {
  # tests for the property `select_category` (V2reportsTranscriptSelectCategory)

  # uncomment below to test the property
  #expect_equal(model.instance$`select_category`, "EXPECTED_RESULT")
})
