# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2DownloadSummaryAvailableFiles")

model_instance <- V2DownloadSummaryAvailableFiles$new()

test_that("all_genomic_fasta", {
  # tests for the property `all_genomic_fasta` (V2DownloadSummaryFileSummary)

  # uncomment below to test the property
  #expect_equal(model.instance$`all_genomic_fasta`, "EXPECTED_RESULT")
})

test_that("genome_gff", {
  # tests for the property `genome_gff` (V2DownloadSummaryFileSummary)

  # uncomment below to test the property
  #expect_equal(model.instance$`genome_gff`, "EXPECTED_RESULT")
})

test_that("genome_gbff", {
  # tests for the property `genome_gbff` (V2DownloadSummaryFileSummary)

  # uncomment below to test the property
  #expect_equal(model.instance$`genome_gbff`, "EXPECTED_RESULT")
})

test_that("rna_fasta", {
  # tests for the property `rna_fasta` (V2DownloadSummaryFileSummary)

  # uncomment below to test the property
  #expect_equal(model.instance$`rna_fasta`, "EXPECTED_RESULT")
})

test_that("prot_fasta", {
  # tests for the property `prot_fasta` (V2DownloadSummaryFileSummary)

  # uncomment below to test the property
  #expect_equal(model.instance$`prot_fasta`, "EXPECTED_RESULT")
})

test_that("genome_gtf", {
  # tests for the property `genome_gtf` (V2DownloadSummaryFileSummary)

  # uncomment below to test the property
  #expect_equal(model.instance$`genome_gtf`, "EXPECTED_RESULT")
})

test_that("cds_fasta", {
  # tests for the property `cds_fasta` (V2DownloadSummaryFileSummary)

  # uncomment below to test the property
  #expect_equal(model.instance$`cds_fasta`, "EXPECTED_RESULT")
})

test_that("sequence_report", {
  # tests for the property `sequence_report` (V2DownloadSummaryFileSummary)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequence_report`, "EXPECTED_RESULT")
})

test_that("annotation_report", {
  # tests for the property `annotation_report` (V2DownloadSummaryFileSummary)

  # uncomment below to test the property
  #expect_equal(model.instance$`annotation_report`, "EXPECTED_RESULT")
})
