# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyFilteredSubtreeRequest")

model_instance <- V2TaxonomyFilteredSubtreeRequest$new()

test_that("taxons", {
  # tests for the property `taxons` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`taxons`, "EXPECTED_RESULT")
})

test_that("specified_limit", {
  # tests for the property `specified_limit` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`specified_limit`, "EXPECTED_RESULT")
})

test_that("rank_limits", {
  # tests for the property `rank_limits` (array[V2reportsRankType])

  # uncomment below to test the property
  #expect_equal(model.instance$`rank_limits`, "EXPECTED_RESULT")
})
