# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsGeneReportMatch")

model_instance <- V2reportsGeneReportMatch$new()

test_that("gene", {
  # tests for the property `gene` (V2reportsGeneDescriptor)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene`, "EXPECTED_RESULT")
})

test_that("product", {
  # tests for the property `product` (V2reportsProductDescriptor)

  # uncomment below to test the property
  #expect_equal(model.instance$`product`, "EXPECTED_RESULT")
})

test_that("query", {
  # tests for the property `query` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`query`, "EXPECTED_RESULT")
})

test_that("warnings", {
  # tests for the property `warnings` (array[V2reportsWarning])

  # uncomment below to test the property
  #expect_equal(model.instance$`warnings`, "EXPECTED_RESULT")
})

test_that("warning", {
  # tests for the property `warning` (V2reportsWarning)

  # uncomment below to test the property
  #expect_equal(model.instance$`warning`, "EXPECTED_RESULT")
})

test_that("errors", {
  # tests for the property `errors` (array[V2reportsError])

  # uncomment below to test the property
  #expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})
