# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2AssemblyCheckMHistogramReplyHistogramInterval")

model_instance <- V2AssemblyCheckMHistogramReplyHistogramInterval$new()

test_that("start_pos", {
  # tests for the property `start_pos` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`start_pos`, "EXPECTED_RESULT")
})

test_that("stop_pos", {
  # tests for the property `stop_pos` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`stop_pos`, "EXPECTED_RESULT")
})

test_that("count", {
  # tests for the property `count` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`count`, "EXPECTED_RESULT")
})
