# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsBioSampleStatus")

model_instance <- V2reportsBioSampleStatus$new()

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("when", {
  # tests for the property `when` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`when`, "EXPECTED_RESULT")
})
