# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2AssemblySequenceReportsRequest")

model_instance <- V2AssemblySequenceReportsRequest$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("chromosomes", {
  # tests for the property `chromosomes` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`chromosomes`, "EXPECTED_RESULT")
})

test_that("role_filters", {
  # tests for the property `role_filters` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`role_filters`, "EXPECTED_RESULT")
})

test_that("table_fields", {
  # tests for the property `table_fields` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`table_fields`, "EXPECTED_RESULT")
})

test_that("count_assembly_unplaced", {
  # tests for the property `count_assembly_unplaced` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`count_assembly_unplaced`, "EXPECTED_RESULT")
})

test_that("page_size", {
  # tests for the property `page_size` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`page_size`, "EXPECTED_RESULT")
})

test_that("page_token", {
  # tests for the property `page_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`page_token`, "EXPECTED_RESULT")
})

test_that("include_tabular_header", {
  # tests for the property `include_tabular_header` (V2IncludeTabularHeader)

  # uncomment below to test the property
  #expect_equal(model.instance$`include_tabular_header`, "EXPECTED_RESULT")
})

test_that("table_format", {
  # tests for the property `table_format` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`table_format`, "EXPECTED_RESULT")
})
