# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsVirusAssemblySubmitterInfo")

model_instance <- V2reportsVirusAssemblySubmitterInfo$new()

test_that("names", {
  # tests for the property `names` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`names`, "EXPECTED_RESULT")
})

test_that("affiliation", {
  # tests for the property `affiliation` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`affiliation`, "EXPECTED_RESULT")
})

test_that("country", {
  # tests for the property `country` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`country`, "EXPECTED_RESULT")
})
