# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyFilteredSubtreeResponseEdge")

model_instance <- V2TaxonomyFilteredSubtreeResponseEdge$new()

test_that("visible_children", {
  # tests for the property `visible_children` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`visible_children`, "EXPECTED_RESULT")
})

test_that("children_status", {
  # tests for the property `children_status` (V2TaxonomyFilteredSubtreeResponseEdgeChildStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`children_status`, "EXPECTED_RESULT")
})
