# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2GeneCountsByTaxonReplyGeneTypeAndCount")

model_instance <- V2GeneCountsByTaxonReplyGeneTypeAndCount$new()

test_that("gene_type", {
  # tests for the property `gene_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_type`, "EXPECTED_RESULT")
})

test_that("count", {
  # tests for the property `count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`count`, "EXPECTED_RESULT")
})
