# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyLinksResponseGenericLink")

model_instance <- V2TaxonomyLinksResponseGenericLink$new()

test_that("link_name", {
  # tests for the property `link_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`link_name`, "EXPECTED_RESULT")
})

test_that("link_url", {
  # tests for the property `link_url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`link_url`, "EXPECTED_RESULT")
})
