# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsConservedDomain")

model_instance <- V2reportsConservedDomain$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("range", {
  # tests for the property `range` (V2reportsRange)

  # uncomment below to test the property
  #expect_equal(model.instance$`range`, "EXPECTED_RESULT")
})
