# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2SleepRequest")

model_instance <- V2SleepRequest$new()

test_that("sleep_msec", {
  # tests for the property `sleep_msec` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`sleep_msec`, "EXPECTED_RESULT")
})

test_that("error_rate", {
  # tests for the property `error_rate` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`error_rate`, "EXPECTED_RESULT")
})
