# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsBuscoStat")

model_instance <- V2reportsBuscoStat$new()

test_that("busco_lineage", {
  # tests for the property `busco_lineage` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`busco_lineage`, "EXPECTED_RESULT")
})

test_that("busco_ver", {
  # tests for the property `busco_ver` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`busco_ver`, "EXPECTED_RESULT")
})

test_that("complete", {
  # tests for the property `complete` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`complete`, "EXPECTED_RESULT")
})

test_that("single_copy", {
  # tests for the property `single_copy` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`single_copy`, "EXPECTED_RESULT")
})

test_that("duplicated", {
  # tests for the property `duplicated` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`duplicated`, "EXPECTED_RESULT")
})

test_that("fragmented", {
  # tests for the property `fragmented` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`fragmented`, "EXPECTED_RESULT")
})

test_that("missing", {
  # tests for the property `missing` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`missing`, "EXPECTED_RESULT")
})

test_that("total_count", {
  # tests for the property `total_count` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_count`, "EXPECTED_RESULT")
})
