# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsAnnotation")

model_instance <- V2reportsAnnotation$new()

test_that("assembly_accession", {
  # tests for the property `assembly_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_accession`, "EXPECTED_RESULT")
})

test_that("assembly_name", {
  # tests for the property `assembly_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_name`, "EXPECTED_RESULT")
})

test_that("annotation_name", {
  # tests for the property `annotation_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`annotation_name`, "EXPECTED_RESULT")
})

test_that("annotation_release_date", {
  # tests for the property `annotation_release_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`annotation_release_date`, "EXPECTED_RESULT")
})

test_that("genomic_locations", {
  # tests for the property `genomic_locations` (array[V2reportsGenomicLocation])

  # uncomment below to test the property
  #expect_equal(model.instance$`genomic_locations`, "EXPECTED_RESULT")
})
