# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2archiveAffiliation")

model_instance <- V2archiveAffiliation$new()

test_that("affiliation", {
  # tests for the property `affiliation` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`affiliation`, "EXPECTED_RESULT")
})

test_that("division", {
  # tests for the property `division` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`division`, "EXPECTED_RESULT")
})

test_that("location", {
  # tests for the property `location` (V2archiveLocation)

  # uncomment below to test the property
  #expect_equal(model.instance$`location`, "EXPECTED_RESULT")
})
