# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2SeqReply")

model_instance <- V2SeqReply$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("seq_length", {
  # tests for the property `seq_length` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`seq_length`, "EXPECTED_RESULT")
})

test_that("mol_type", {
  # tests for the property `mol_type` (V2MolType)

  # uncomment below to test the property
  #expect_equal(model.instance$`mol_type`, "EXPECTED_RESULT")
})

test_that("defline", {
  # tests for the property `defline` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`defline`, "EXPECTED_RESULT")
})

test_that("sequence", {
  # tests for the property `sequence` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequence`, "EXPECTED_RESULT")
})
