# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test BioSampleApi")

api_instance <- BioSampleApi$new()

test_that("BioSampleDatasetReport", {
  # tests for BioSampleDatasetReport
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get BioSample dataset reports by accession(s)
  # Get BioSample dataset reports by accession(s).  By default, in paged JSON format, but also available as tabular (accept: text/tab-separated-values) or json-lines (accept: application/x-ndjson)
  # @param accessions array[character] 
  # @return [V2reportsBioSampleDataReportPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
