# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2AssemblyCheckMHistogramRequest")

model_instance <- V2AssemblyCheckMHistogramRequest$new()

test_that("species_taxon", {
  # tests for the property `species_taxon` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`species_taxon`, "EXPECTED_RESULT")
})
