# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsTaxonomyNamesDescriptorCitation")

model_instance <- V2reportsTaxonomyNamesDescriptorCitation$new()

test_that("full_citation", {
  # tests for the property `full_citation` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`full_citation`, "EXPECTED_RESULT")
})

test_that("short_citation", {
  # tests for the property `short_citation` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`short_citation`, "EXPECTED_RESULT")
})

test_that("pmid", {
  # tests for the property `pmid` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`pmid`, "EXPECTED_RESULT")
})
