# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyFilteredSubtreeResponse")

model_instance <- V2TaxonomyFilteredSubtreeResponse$new()

test_that("root_nodes", {
  # tests for the property `root_nodes` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`root_nodes`, "EXPECTED_RESULT")
})

test_that("edges", {
  # tests for the property `edges` (V2TaxonomyFilteredSubtreeResponseEdgesEntry)

  # uncomment below to test the property
  #expect_equal(model.instance$`edges`, "EXPECTED_RESULT")
})

test_that("warnings", {
  # tests for the property `warnings` (array[V2reportsWarning])

  # uncomment below to test the property
  #expect_equal(model.instance$`warnings`, "EXPECTED_RESULT")
})

test_that("errors", {
  # tests for the property `errors` (array[V2reportsError])

  # uncomment below to test the property
  #expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})
