# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2archiveTaxonomyNode")

model_instance <- V2archiveTaxonomyNode$new()

test_that("tax_id", {
  # tests for the property `tax_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_id`, "EXPECTED_RESULT")
})

test_that("current_scientific_name", {
  # tests for the property `current_scientific_name` (V2reportsNameAndAuthority)

  # uncomment below to test the property
  #expect_equal(model.instance$`current_scientific_name`, "EXPECTED_RESULT")
})

test_that("basionym", {
  # tests for the property `basionym` (V2reportsNameAndAuthority)

  # uncomment below to test the property
  #expect_equal(model.instance$`basionym`, "EXPECTED_RESULT")
})

test_that("curator_common_name", {
  # tests for the property `curator_common_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`curator_common_name`, "EXPECTED_RESULT")
})

test_that("group_name", {
  # tests for the property `group_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`group_name`, "EXPECTED_RESULT")
})

test_that("classification", {
  # tests for the property `classification` (V2reportsClassification)

  # uncomment below to test the property
  #expect_equal(model.instance$`classification`, "EXPECTED_RESULT")
})

test_that("modifiers", {
  # tests for the property `modifiers` (array[V2archiveModifier])

  # uncomment below to test the property
  #expect_equal(model.instance$`modifiers`, "EXPECTED_RESULT")
})
