# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2HttpBody")

model_instance <- V2HttpBody$new()

test_that("content_type", {
  # tests for the property `content_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`content_type`, "EXPECTED_RESULT")
})

test_that("data", {
  # tests for the property `data` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})
