# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsWarning")

model_instance <- V2reportsWarning$new()

test_that("gene_warning_code", {
  # tests for the property `gene_warning_code` (V2reportsWarningGeneWarningCode)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_warning_code`, "EXPECTED_RESULT")
})

test_that("reason", {
  # tests for the property `reason` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`reason`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("replaced_id", {
  # tests for the property `replaced_id` (V2reportsWarningReplacedId)

  # uncomment below to test the property
  #expect_equal(model.instance$`replaced_id`, "EXPECTED_RESULT")
})

test_that("unrecognized_identifier", {
  # tests for the property `unrecognized_identifier` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`unrecognized_identifier`, "EXPECTED_RESULT")
})
