# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2archiveName")

model_instance <- V2archiveName$new()

test_that("first", {
  # tests for the property `first` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`first`, "EXPECTED_RESULT")
})

test_that("middle", {
  # tests for the property `middle` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`middle`, "EXPECTED_RESULT")
})

test_that("last", {
  # tests for the property `last` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`last`, "EXPECTED_RESULT")
})

test_that("full", {
  # tests for the property `full` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`full`, "EXPECTED_RESULT")
})

test_that("initials", {
  # tests for the property `initials` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`initials`, "EXPECTED_RESULT")
})

test_that("suffix", {
  # tests for the property `suffix` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`suffix`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("affiliation", {
  # tests for the property `affiliation` (V2archiveAffiliation)

  # uncomment below to test the property
  #expect_equal(model.instance$`affiliation`, "EXPECTED_RESULT")
})
