# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsAverageNucleotideIdentity")

model_instance <- V2reportsAverageNucleotideIdentity$new()

test_that("taxonomy_check_status", {
  # tests for the property `taxonomy_check_status` (V2reportsAverageNucleotideIdentityTaxonomyCheckStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxonomy_check_status`, "EXPECTED_RESULT")
})

test_that("match_status", {
  # tests for the property `match_status` (V2reportsAverageNucleotideIdentityMatchStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`match_status`, "EXPECTED_RESULT")
})

test_that("submitted_organism", {
  # tests for the property `submitted_organism` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`submitted_organism`, "EXPECTED_RESULT")
})

test_that("submitted_species", {
  # tests for the property `submitted_species` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`submitted_species`, "EXPECTED_RESULT")
})

test_that("category", {
  # tests for the property `category` (V2reportsANITypeCategory)

  # uncomment below to test the property
  #expect_equal(model.instance$`category`, "EXPECTED_RESULT")
})

test_that("submitted_ani_match", {
  # tests for the property `submitted_ani_match` (V2reportsANIMatch)

  # uncomment below to test the property
  #expect_equal(model.instance$`submitted_ani_match`, "EXPECTED_RESULT")
})

test_that("best_ani_match", {
  # tests for the property `best_ani_match` (V2reportsANIMatch)

  # uncomment below to test the property
  #expect_equal(model.instance$`best_ani_match`, "EXPECTED_RESULT")
})

test_that("comment", {
  # tests for the property `comment` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`comment`, "EXPECTED_RESULT")
})
