# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsVirusAssemblyCollectionLocation")

model_instance <- V2reportsVirusAssemblyCollectionLocation$new()

test_that("geographic_location", {
  # tests for the property `geographic_location` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`geographic_location`, "EXPECTED_RESULT")
})

test_that("geographic_region", {
  # tests for the property `geographic_region` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`geographic_region`, "EXPECTED_RESULT")
})

test_that("usa_state", {
  # tests for the property `usa_state` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`usa_state`, "EXPECTED_RESULT")
})
