# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2archiveSequence")

model_instance <- V2archiveSequence$new()

test_that("length", {
  # tests for the property `length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`length`, "EXPECTED_RESULT")
})

test_that("units", {
  # tests for the property `units` (V2archiveSequenceLengthUnits)

  # uncomment below to test the property
  #expect_equal(model.instance$`units`, "EXPECTED_RESULT")
})
