# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsANIMatch")

model_instance <- V2reportsANIMatch$new()

test_that("assembly", {
  # tests for the property `assembly` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly`, "EXPECTED_RESULT")
})

test_that("organism_name", {
  # tests for the property `organism_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`organism_name`, "EXPECTED_RESULT")
})

test_that("category", {
  # tests for the property `category` (V2reportsANITypeCategory)

  # uncomment below to test the property
  #expect_equal(model.instance$`category`, "EXPECTED_RESULT")
})

test_that("ani", {
  # tests for the property `ani` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`ani`, "EXPECTED_RESULT")
})

test_that("assembly_coverage", {
  # tests for the property `assembly_coverage` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_coverage`, "EXPECTED_RESULT")
})

test_that("type_assembly_coverage", {
  # tests for the property `type_assembly_coverage` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`type_assembly_coverage`, "EXPECTED_RESULT")
})
