# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsProductDescriptor")

model_instance <- V2reportsProductDescriptor$new()

test_that("gene_id", {
  # tests for the property `gene_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_id`, "EXPECTED_RESULT")
})

test_that("symbol", {
  # tests for the property `symbol` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`symbol`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("tax_id", {
  # tests for the property `tax_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_id`, "EXPECTED_RESULT")
})

test_that("taxname", {
  # tests for the property `taxname` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxname`, "EXPECTED_RESULT")
})

test_that("common_name", {
  # tests for the property `common_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`common_name`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (V2reportsGeneType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("rna_type", {
  # tests for the property `rna_type` (V2reportsRnaType)

  # uncomment below to test the property
  #expect_equal(model.instance$`rna_type`, "EXPECTED_RESULT")
})

test_that("transcripts", {
  # tests for the property `transcripts` (array[V2reportsTranscript])

  # uncomment below to test the property
  #expect_equal(model.instance$`transcripts`, "EXPECTED_RESULT")
})

test_that("transcript_count", {
  # tests for the property `transcript_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`transcript_count`, "EXPECTED_RESULT")
})

test_that("protein_count", {
  # tests for the property `protein_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`protein_count`, "EXPECTED_RESULT")
})

test_that("transcript_type_counts", {
  # tests for the property `transcript_type_counts` (array[V2reportsTranscriptTypeCount])

  # uncomment below to test the property
  #expect_equal(model.instance$`transcript_type_counts`, "EXPECTED_RESULT")
})
