# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsBioProject")

model_instance <- V2reportsBioProject$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("parent_accession", {
  # tests for the property `parent_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`parent_accession`, "EXPECTED_RESULT")
})

test_that("parent_accessions", {
  # tests for the property `parent_accessions` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`parent_accessions`, "EXPECTED_RESULT")
})
