# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsAssemblyDataReport")

model_instance <- V2reportsAssemblyDataReport$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("current_accession", {
  # tests for the property `current_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`current_accession`, "EXPECTED_RESULT")
})

test_that("paired_accession", {
  # tests for the property `paired_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`paired_accession`, "EXPECTED_RESULT")
})

test_that("source_database", {
  # tests for the property `source_database` (V2reportsSourceDatabase)

  # uncomment below to test the property
  #expect_equal(model.instance$`source_database`, "EXPECTED_RESULT")
})

test_that("organism", {
  # tests for the property `organism` (V2reportsOrganism)

  # uncomment below to test the property
  #expect_equal(model.instance$`organism`, "EXPECTED_RESULT")
})

test_that("assembly_info", {
  # tests for the property `assembly_info` (V2reportsAssemblyInfo)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_info`, "EXPECTED_RESULT")
})

test_that("assembly_stats", {
  # tests for the property `assembly_stats` (V2reportsAssemblyStats)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_stats`, "EXPECTED_RESULT")
})

test_that("organelle_info", {
  # tests for the property `organelle_info` (array[V2reportsOrganelleInfo])

  # uncomment below to test the property
  #expect_equal(model.instance$`organelle_info`, "EXPECTED_RESULT")
})

test_that("additional_submitters", {
  # tests for the property `additional_submitters` (array[V2reportsAdditionalSubmitter])

  # uncomment below to test the property
  #expect_equal(model.instance$`additional_submitters`, "EXPECTED_RESULT")
})

test_that("annotation_info", {
  # tests for the property `annotation_info` (V2reportsAnnotationInfo)

  # uncomment below to test the property
  #expect_equal(model.instance$`annotation_info`, "EXPECTED_RESULT")
})

test_that("wgs_info", {
  # tests for the property `wgs_info` (V2reportsWGSInfo)

  # uncomment below to test the property
  #expect_equal(model.instance$`wgs_info`, "EXPECTED_RESULT")
})

test_that("type_material", {
  # tests for the property `type_material` (V2reportsTypeMaterial)

  # uncomment below to test the property
  #expect_equal(model.instance$`type_material`, "EXPECTED_RESULT")
})

test_that("checkm_info", {
  # tests for the property `checkm_info` (V2reportsCheckM)

  # uncomment below to test the property
  #expect_equal(model.instance$`checkm_info`, "EXPECTED_RESULT")
})

test_that("average_nucleotide_identity", {
  # tests for the property `average_nucleotide_identity` (V2reportsAverageNucleotideIdentity)

  # uncomment below to test the property
  #expect_equal(model.instance$`average_nucleotide_identity`, "EXPECTED_RESULT")
})
