# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2VirusAvailabilityRequest")

model_instance <- V2VirusAvailabilityRequest$new()

test_that("accessions", {
  # tests for the property `accessions` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`accessions`, "EXPECTED_RESULT")
})
