# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsNomenclatureAuthority")

model_instance <- V2reportsNomenclatureAuthority$new()

test_that("authority", {
  # tests for the property `authority` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`authority`, "EXPECTED_RESULT")
})

test_that("identifier", {
  # tests for the property `identifier` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`identifier`, "EXPECTED_RESULT")
})
