# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2ProkaryoteGeneRequest")

model_instance <- V2ProkaryoteGeneRequest$new()

test_that("accessions", {
  # tests for the property `accessions` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`accessions`, "EXPECTED_RESULT")
})

test_that("include_annotation_type", {
  # tests for the property `include_annotation_type` (array[V2Fasta])

  # uncomment below to test the property
  #expect_equal(model.instance$`include_annotation_type`, "EXPECTED_RESULT")
})

test_that("gene_flank_config", {
  # tests for the property `gene_flank_config` (V2ProkaryoteGeneRequestGeneFlankConfig)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_flank_config`, "EXPECTED_RESULT")
})

test_that("taxon", {
  # tests for the property `taxon` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon`, "EXPECTED_RESULT")
})
