# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsFeatureCounts")

model_instance <- V2reportsFeatureCounts$new()

test_that("gene_counts", {
  # tests for the property `gene_counts` (V2reportsGeneCounts)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_counts`, "EXPECTED_RESULT")
})
