# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2VirusDataReportRequest")

model_instance <- V2VirusDataReportRequest$new()

test_that("filter", {
  # tests for the property `filter` (V2VirusDatasetFilter)

  # uncomment below to test the property
  #expect_equal(model.instance$`filter`, "EXPECTED_RESULT")
})

test_that("returned_content", {
  # tests for the property `returned_content` (V2VirusDataReportRequestContentType)

  # uncomment below to test the property
  #expect_equal(model.instance$`returned_content`, "EXPECTED_RESULT")
})

test_that("table_fields", {
  # tests for the property `table_fields` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`table_fields`, "EXPECTED_RESULT")
})

test_that("table_format", {
  # tests for the property `table_format` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`table_format`, "EXPECTED_RESULT")
})

test_that("page_size", {
  # tests for the property `page_size` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`page_size`, "EXPECTED_RESULT")
})

test_that("page_token", {
  # tests for the property `page_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`page_token`, "EXPECTED_RESULT")
})
