# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsOrganelleDataReports")

model_instance <- V2reportsOrganelleDataReports$new()

test_that("messages", {
  # tests for the property `messages` (array[V2reportsMessage])

  # uncomment below to test the property
  #expect_equal(model.instance$`messages`, "EXPECTED_RESULT")
})

test_that("reports", {
  # tests for the property `reports` (array[V2reportsOrganelle])

  # uncomment below to test the property
  #expect_equal(model.instance$`reports`, "EXPECTED_RESULT")
})

test_that("total_count", {
  # tests for the property `total_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_count`, "EXPECTED_RESULT")
})

test_that("next_page_token", {
  # tests for the property `next_page_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`next_page_token`, "EXPECTED_RESULT")
})
