# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsSequenceInfo")

model_instance <- V2reportsSequenceInfo$new()

test_that("assembly_accession", {
  # tests for the property `assembly_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_accession`, "EXPECTED_RESULT")
})

test_that("chr_name", {
  # tests for the property `chr_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`chr_name`, "EXPECTED_RESULT")
})

test_that("ucsc_style_name", {
  # tests for the property `ucsc_style_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ucsc_style_name`, "EXPECTED_RESULT")
})

test_that("sort_order", {
  # tests for the property `sort_order` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`sort_order`, "EXPECTED_RESULT")
})

test_that("assigned_molecule_location_type", {
  # tests for the property `assigned_molecule_location_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assigned_molecule_location_type`, "EXPECTED_RESULT")
})

test_that("refseq_accession", {
  # tests for the property `refseq_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`refseq_accession`, "EXPECTED_RESULT")
})

test_that("assembly_unit", {
  # tests for the property `assembly_unit` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_unit`, "EXPECTED_RESULT")
})

test_that("length", {
  # tests for the property `length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`length`, "EXPECTED_RESULT")
})

test_that("genbank_accession", {
  # tests for the property `genbank_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`genbank_accession`, "EXPECTED_RESULT")
})

test_that("gc_count", {
  # tests for the property `gc_count` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`gc_count`, "EXPECTED_RESULT")
})

test_that("gc_percent", {
  # tests for the property `gc_percent` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`gc_percent`, "EXPECTED_RESULT")
})

test_that("unlocalized_count", {
  # tests for the property `unlocalized_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`unlocalized_count`, "EXPECTED_RESULT")
})

test_that("assembly_unplaced_count", {
  # tests for the property `assembly_unplaced_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_unplaced_count`, "EXPECTED_RESULT")
})

test_that("role", {
  # tests for the property `role` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`role`, "EXPECTED_RESULT")
})

test_that("sequence_name", {
  # tests for the property `sequence_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequence_name`, "EXPECTED_RESULT")
})
