# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2ProkaryoteGeneRequestGeneFlankConfig")

model_instance <- V2ProkaryoteGeneRequestGeneFlankConfig$new()

test_that("length", {
  # tests for the property `length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`length`, "EXPECTED_RESULT")
})
