# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyImageRequest")

model_instance <- V2TaxonomyImageRequest$new()

test_that("taxon", {
  # tests for the property `taxon` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon`, "EXPECTED_RESULT")
})

test_that("image_size", {
  # tests for the property `image_size` (V2ImageSize)

  # uncomment below to test the property
  #expect_equal(model.instance$`image_size`, "EXPECTED_RESULT")
})
