# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsSequenceInformation")

model_instance <- V2reportsSequenceInformation$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("submission_date", {
  # tests for the property `submission_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`submission_date`, "EXPECTED_RESULT")
})

test_that("submitter", {
  # tests for the property `submitter` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`submitter`, "EXPECTED_RESULT")
})
