# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyImageMetadataResponse")

model_instance <- V2TaxonomyImageMetadataResponse$new()

test_that("tax_id", {
  # tests for the property `tax_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_id`, "EXPECTED_RESULT")
})

test_that("src", {
  # tests for the property `src` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`src`, "EXPECTED_RESULT")
})

test_that("license", {
  # tests for the property `license` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`license`, "EXPECTED_RESULT")
})

test_that("attribution", {
  # tests for the property `attribution` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`attribution`, "EXPECTED_RESULT")
})

test_that("source", {
  # tests for the property `source` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`source`, "EXPECTED_RESULT")
})

test_that("image_sizes", {
  # tests for the property `image_sizes` (array[V2ImageSize])

  # uncomment below to test the property
  #expect_equal(model.instance$`image_sizes`, "EXPECTED_RESULT")
})

test_that("format", {
  # tests for the property `format` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`format`, "EXPECTED_RESULT")
})
