# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsBioSampleDescriptor")

model_instance <- V2reportsBioSampleDescriptor$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("last_updated", {
  # tests for the property `last_updated` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`last_updated`, "EXPECTED_RESULT")
})

test_that("publication_date", {
  # tests for the property `publication_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`publication_date`, "EXPECTED_RESULT")
})

test_that("submission_date", {
  # tests for the property `submission_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`submission_date`, "EXPECTED_RESULT")
})

test_that("sample_ids", {
  # tests for the property `sample_ids` (array[V2reportsBioSampleId])

  # uncomment below to test the property
  #expect_equal(model.instance$`sample_ids`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (V2reportsBioSampleDescription)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("owner", {
  # tests for the property `owner` (V2reportsBioSampleOwner)

  # uncomment below to test the property
  #expect_equal(model.instance$`owner`, "EXPECTED_RESULT")
})

test_that("models", {
  # tests for the property `models` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`models`, "EXPECTED_RESULT")
})

test_that("bioprojects", {
  # tests for the property `bioprojects` (array[V2reportsBioProject])

  # uncomment below to test the property
  #expect_equal(model.instance$`bioprojects`, "EXPECTED_RESULT")
})

test_that("package", {
  # tests for the property `package` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`package`, "EXPECTED_RESULT")
})

test_that("attributes", {
  # tests for the property `attributes` (array[V2reportsBioSampleAttribute])

  # uncomment below to test the property
  #expect_equal(model.instance$`attributes`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (V2reportsBioSampleStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("age", {
  # tests for the property `age` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`age`, "EXPECTED_RESULT")
})

test_that("biomaterial_provider", {
  # tests for the property `biomaterial_provider` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`biomaterial_provider`, "EXPECTED_RESULT")
})

test_that("breed", {
  # tests for the property `breed` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`breed`, "EXPECTED_RESULT")
})

test_that("collected_by", {
  # tests for the property `collected_by` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`collected_by`, "EXPECTED_RESULT")
})

test_that("collection_date", {
  # tests for the property `collection_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`collection_date`, "EXPECTED_RESULT")
})

test_that("cultivar", {
  # tests for the property `cultivar` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`cultivar`, "EXPECTED_RESULT")
})

test_that("dev_stage", {
  # tests for the property `dev_stage` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`dev_stage`, "EXPECTED_RESULT")
})

test_that("ecotype", {
  # tests for the property `ecotype` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ecotype`, "EXPECTED_RESULT")
})

test_that("geo_loc_name", {
  # tests for the property `geo_loc_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`geo_loc_name`, "EXPECTED_RESULT")
})

test_that("host", {
  # tests for the property `host` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`host`, "EXPECTED_RESULT")
})

test_that("host_disease", {
  # tests for the property `host_disease` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`host_disease`, "EXPECTED_RESULT")
})

test_that("identified_by", {
  # tests for the property `identified_by` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`identified_by`, "EXPECTED_RESULT")
})

test_that("ifsac_category", {
  # tests for the property `ifsac_category` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ifsac_category`, "EXPECTED_RESULT")
})

test_that("isolate", {
  # tests for the property `isolate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isolate`, "EXPECTED_RESULT")
})

test_that("isolate_name_alias", {
  # tests for the property `isolate_name_alias` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isolate_name_alias`, "EXPECTED_RESULT")
})

test_that("isolation_source", {
  # tests for the property `isolation_source` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isolation_source`, "EXPECTED_RESULT")
})

test_that("lat_lon", {
  # tests for the property `lat_lon` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lat_lon`, "EXPECTED_RESULT")
})

test_that("project_name", {
  # tests for the property `project_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`project_name`, "EXPECTED_RESULT")
})

test_that("sample_name", {
  # tests for the property `sample_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sample_name`, "EXPECTED_RESULT")
})

test_that("serovar", {
  # tests for the property `serovar` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`serovar`, "EXPECTED_RESULT")
})

test_that("sex", {
  # tests for the property `sex` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sex`, "EXPECTED_RESULT")
})

test_that("source_type", {
  # tests for the property `source_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`source_type`, "EXPECTED_RESULT")
})

test_that("strain", {
  # tests for the property `strain` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`strain`, "EXPECTED_RESULT")
})

test_that("sub_species", {
  # tests for the property `sub_species` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sub_species`, "EXPECTED_RESULT")
})

test_that("tissue", {
  # tests for the property `tissue` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tissue`, "EXPECTED_RESULT")
})

test_that("serotype", {
  # tests for the property `serotype` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`serotype`, "EXPECTED_RESULT")
})
