# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsClassification")

model_instance <- V2reportsClassification$new()

test_that("superkingdom", {
  # tests for the property `superkingdom` (V2reportsTaxData)

  # uncomment below to test the property
  #expect_equal(model.instance$`superkingdom`, "EXPECTED_RESULT")
})

test_that("kingdom", {
  # tests for the property `kingdom` (V2reportsTaxData)

  # uncomment below to test the property
  #expect_equal(model.instance$`kingdom`, "EXPECTED_RESULT")
})

test_that("phylum", {
  # tests for the property `phylum` (V2reportsTaxData)

  # uncomment below to test the property
  #expect_equal(model.instance$`phylum`, "EXPECTED_RESULT")
})

test_that("class", {
  # tests for the property `class` (V2reportsTaxData)

  # uncomment below to test the property
  #expect_equal(model.instance$`class`, "EXPECTED_RESULT")
})

test_that("order", {
  # tests for the property `order` (V2reportsTaxData)

  # uncomment below to test the property
  #expect_equal(model.instance$`order`, "EXPECTED_RESULT")
})

test_that("family", {
  # tests for the property `family` (V2reportsTaxData)

  # uncomment below to test the property
  #expect_equal(model.instance$`family`, "EXPECTED_RESULT")
})

test_that("genus", {
  # tests for the property `genus` (V2reportsTaxData)

  # uncomment below to test the property
  #expect_equal(model.instance$`genus`, "EXPECTED_RESULT")
})

test_that("species", {
  # tests for the property `species` (V2reportsTaxData)

  # uncomment below to test the property
  #expect_equal(model.instance$`species`, "EXPECTED_RESULT")
})

test_that("domain", {
  # tests for the property `domain` (V2reportsTaxData)

  # uncomment below to test the property
  #expect_equal(model.instance$`domain`, "EXPECTED_RESULT")
})

test_that("realm", {
  # tests for the property `realm` (V2reportsTaxData)

  # uncomment below to test the property
  #expect_equal(model.instance$`realm`, "EXPECTED_RESULT")
})

test_that("acellular_root", {
  # tests for the property `acellular_root` (V2reportsTaxData)

  # uncomment below to test the property
  #expect_equal(model.instance$`acellular_root`, "EXPECTED_RESULT")
})
