# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsBioSampleDescription")

model_instance <- V2reportsBioSampleDescription$new()

test_that("title", {
  # tests for the property `title` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("organism", {
  # tests for the property `organism` (V2reportsOrganism)

  # uncomment below to test the property
  #expect_equal(model.instance$`organism`, "EXPECTED_RESULT")
})

test_that("comment", {
  # tests for the property `comment` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`comment`, "EXPECTED_RESULT")
})
