# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsAssemblyStats")

model_instance <- V2reportsAssemblyStats$new()

test_that("total_number_of_chromosomes", {
  # tests for the property `total_number_of_chromosomes` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_number_of_chromosomes`, "EXPECTED_RESULT")
})

test_that("total_sequence_length", {
  # tests for the property `total_sequence_length` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_sequence_length`, "EXPECTED_RESULT")
})

test_that("total_ungapped_length", {
  # tests for the property `total_ungapped_length` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_ungapped_length`, "EXPECTED_RESULT")
})

test_that("number_of_contigs", {
  # tests for the property `number_of_contigs` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`number_of_contigs`, "EXPECTED_RESULT")
})

test_that("contig_n50", {
  # tests for the property `contig_n50` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`contig_n50`, "EXPECTED_RESULT")
})

test_that("contig_l50", {
  # tests for the property `contig_l50` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`contig_l50`, "EXPECTED_RESULT")
})

test_that("number_of_scaffolds", {
  # tests for the property `number_of_scaffolds` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`number_of_scaffolds`, "EXPECTED_RESULT")
})

test_that("scaffold_n50", {
  # tests for the property `scaffold_n50` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`scaffold_n50`, "EXPECTED_RESULT")
})

test_that("scaffold_l50", {
  # tests for the property `scaffold_l50` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`scaffold_l50`, "EXPECTED_RESULT")
})

test_that("gaps_between_scaffolds_count", {
  # tests for the property `gaps_between_scaffolds_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`gaps_between_scaffolds_count`, "EXPECTED_RESULT")
})

test_that("number_of_component_sequences", {
  # tests for the property `number_of_component_sequences` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`number_of_component_sequences`, "EXPECTED_RESULT")
})

test_that("atgc_count", {
  # tests for the property `atgc_count` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`atgc_count`, "EXPECTED_RESULT")
})

test_that("gc_count", {
  # tests for the property `gc_count` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`gc_count`, "EXPECTED_RESULT")
})

test_that("gc_percent", {
  # tests for the property `gc_percent` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`gc_percent`, "EXPECTED_RESULT")
})

test_that("genome_coverage", {
  # tests for the property `genome_coverage` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`genome_coverage`, "EXPECTED_RESULT")
})

test_that("number_of_organelles", {
  # tests for the property `number_of_organelles` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`number_of_organelles`, "EXPECTED_RESULT")
})
