# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2archiveSubmitter")

model_instance <- V2archiveSubmitter$new()

test_that("name", {
  # tests for the property `name` (array[V2archiveName])

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("role", {
  # tests for the property `role` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`role`, "EXPECTED_RESULT")
})

test_that("affiliation", {
  # tests for the property `affiliation` (V2archiveAffiliation)

  # uncomment below to test the property
  #expect_equal(model.instance$`affiliation`, "EXPECTED_RESULT")
})

test_that("date", {
  # tests for the property `date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})
