# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VersionApi")

api_instance <- VersionApi$new()

test_that("Version", {
  # tests for Version
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Retrieve service version
  # Retrieve the latest version of the Datasets services.
  # @return [V2VersionReply]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
