# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2AssemblyCheckMHistogramReply")

model_instance <- V2AssemblyCheckMHistogramReply$new()

test_that("species_taxid", {
  # tests for the property `species_taxid` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`species_taxid`, "EXPECTED_RESULT")
})

test_that("histogram_intervals", {
  # tests for the property `histogram_intervals` (array[V2AssemblyCheckMHistogramReplyHistogramInterval])

  # uncomment below to test the property
  #expect_equal(model.instance$`histogram_intervals`, "EXPECTED_RESULT")
})
