# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2archiveCatalog")

model_instance <- V2archiveCatalog$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("molecule_type", {
  # tests for the property `molecule_type` (V2archiveMoleculeType)

  # uncomment below to test the property
  #expect_equal(model.instance$`molecule_type`, "EXPECTED_RESULT")
})

test_that("definition", {
  # tests for the property `definition` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`definition`, "EXPECTED_RESULT")
})

test_that("taxonomy", {
  # tests for the property `taxonomy` (V2archiveTaxonomyNode)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxonomy`, "EXPECTED_RESULT")
})

test_that("sequence", {
  # tests for the property `sequence` (V2archiveSequence)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequence`, "EXPECTED_RESULT")
})

test_that("topology", {
  # tests for the property `topology` (V2reportsOrganelleTopology)

  # uncomment below to test the property
  #expect_equal(model.instance$`topology`, "EXPECTED_RESULT")
})

test_that("modification_date", {
  # tests for the property `modification_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`modification_date`, "EXPECTED_RESULT")
})

test_that("publication_date", {
  # tests for the property `publication_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`publication_date`, "EXPECTED_RESULT")
})

test_that("submitters", {
  # tests for the property `submitters` (array[V2archiveSubmitter])

  # uncomment below to test the property
  #expect_equal(model.instance$`submitters`, "EXPECTED_RESULT")
})
