# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsPairedAssembly")

model_instance <- V2reportsPairedAssembly$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (V2reportsAssemblyStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("annotation_name", {
  # tests for the property `annotation_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`annotation_name`, "EXPECTED_RESULT")
})

test_that("only_genbank", {
  # tests for the property `only_genbank` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`only_genbank`, "EXPECTED_RESULT")
})

test_that("only_refseq", {
  # tests for the property `only_refseq` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`only_refseq`, "EXPECTED_RESULT")
})

test_that("changed", {
  # tests for the property `changed` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`changed`, "EXPECTED_RESULT")
})

test_that("manual_diff", {
  # tests for the property `manual_diff` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`manual_diff`, "EXPECTED_RESULT")
})

test_that("refseq_genbank_are_different", {
  # tests for the property `refseq_genbank_are_different` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`refseq_genbank_are_different`, "EXPECTED_RESULT")
})

test_that("differences", {
  # tests for the property `differences` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`differences`, "EXPECTED_RESULT")
})
