# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsVirusAssembly")

model_instance <- V2reportsVirusAssembly$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("is_complete", {
  # tests for the property `is_complete` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_complete`, "EXPECTED_RESULT")
})

test_that("is_annotated", {
  # tests for the property `is_annotated` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_annotated`, "EXPECTED_RESULT")
})

test_that("isolate", {
  # tests for the property `isolate` (V2reportsIsolate)

  # uncomment below to test the property
  #expect_equal(model.instance$`isolate`, "EXPECTED_RESULT")
})

test_that("source_database", {
  # tests for the property `source_database` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`source_database`, "EXPECTED_RESULT")
})

test_that("protein_count", {
  # tests for the property `protein_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`protein_count`, "EXPECTED_RESULT")
})

test_that("host", {
  # tests for the property `host` (V2reportsOrganism)

  # uncomment below to test the property
  #expect_equal(model.instance$`host`, "EXPECTED_RESULT")
})

test_that("virus", {
  # tests for the property `virus` (V2reportsOrganism)

  # uncomment below to test the property
  #expect_equal(model.instance$`virus`, "EXPECTED_RESULT")
})

test_that("bioprojects", {
  # tests for the property `bioprojects` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`bioprojects`, "EXPECTED_RESULT")
})

test_that("location", {
  # tests for the property `location` (V2reportsVirusAssemblyCollectionLocation)

  # uncomment below to test the property
  #expect_equal(model.instance$`location`, "EXPECTED_RESULT")
})

test_that("update_date", {
  # tests for the property `update_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`update_date`, "EXPECTED_RESULT")
})

test_that("release_date", {
  # tests for the property `release_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`release_date`, "EXPECTED_RESULT")
})

test_that("nucleotide_completeness", {
  # tests for the property `nucleotide_completeness` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`nucleotide_completeness`, "EXPECTED_RESULT")
})

test_that("completeness", {
  # tests for the property `completeness` (V2reportsVirusAssemblyCompleteness)

  # uncomment below to test the property
  #expect_equal(model.instance$`completeness`, "EXPECTED_RESULT")
})

test_that("length", {
  # tests for the property `length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`length`, "EXPECTED_RESULT")
})

test_that("gene_count", {
  # tests for the property `gene_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_count`, "EXPECTED_RESULT")
})

test_that("mature_peptide_count", {
  # tests for the property `mature_peptide_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`mature_peptide_count`, "EXPECTED_RESULT")
})

test_that("biosample", {
  # tests for the property `biosample` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`biosample`, "EXPECTED_RESULT")
})

test_that("mol_type", {
  # tests for the property `mol_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`mol_type`, "EXPECTED_RESULT")
})

test_that("nucleotide", {
  # tests for the property `nucleotide` (V2reportsSeqRangeSetFasta)

  # uncomment below to test the property
  #expect_equal(model.instance$`nucleotide`, "EXPECTED_RESULT")
})

test_that("purpose_of_sampling", {
  # tests for the property `purpose_of_sampling` (V2reportsPurposeOfSampling)

  # uncomment below to test the property
  #expect_equal(model.instance$`purpose_of_sampling`, "EXPECTED_RESULT")
})

test_that("sra_accessions", {
  # tests for the property `sra_accessions` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`sra_accessions`, "EXPECTED_RESULT")
})

test_that("submitter", {
  # tests for the property `submitter` (V2reportsVirusAssemblySubmitterInfo)

  # uncomment below to test the property
  #expect_equal(model.instance$`submitter`, "EXPECTED_RESULT")
})

test_that("lab_host", {
  # tests for the property `lab_host` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lab_host`, "EXPECTED_RESULT")
})

test_that("is_lab_host", {
  # tests for the property `is_lab_host` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_lab_host`, "EXPECTED_RESULT")
})

test_that("is_vaccine_strain", {
  # tests for the property `is_vaccine_strain` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_vaccine_strain`, "EXPECTED_RESULT")
})

test_that("segment", {
  # tests for the property `segment` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`segment`, "EXPECTED_RESULT")
})
