# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2archiveLocation")

model_instance <- V2archiveLocation$new()

test_that("city", {
  # tests for the property `city` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`city`, "EXPECTED_RESULT")
})

test_that("sub", {
  # tests for the property `sub` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sub`, "EXPECTED_RESULT")
})

test_that("country", {
  # tests for the property `country` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`country`, "EXPECTED_RESULT")
})

test_that("street", {
  # tests for the property `street` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`street`, "EXPECTED_RESULT")
})

test_that("postal_code", {
  # tests for the property `postal_code` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`postal_code`, "EXPECTED_RESULT")
})
