# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyMatch")

model_instance <- V2TaxonomyMatch$new()

test_that("warnings", {
  # tests for the property `warnings` (array[V2reportsWarning])

  # uncomment below to test the property
  #expect_equal(model.instance$`warnings`, "EXPECTED_RESULT")
})

test_that("errors", {
  # tests for the property `errors` (array[V2reportsError])

  # uncomment below to test the property
  #expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})

test_that("query", {
  # tests for the property `query` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`query`, "EXPECTED_RESULT")
})

test_that("taxonomy", {
  # tests for the property `taxonomy` (V2TaxonomyNode)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxonomy`, "EXPECTED_RESULT")
})
