# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsWGSInfo")

model_instance <- V2reportsWGSInfo$new()

test_that("wgs_project_accession", {
  # tests for the property `wgs_project_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wgs_project_accession`, "EXPECTED_RESULT")
})

test_that("master_wgs_url", {
  # tests for the property `master_wgs_url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`master_wgs_url`, "EXPECTED_RESULT")
})

test_that("wgs_contigs_url", {
  # tests for the property `wgs_contigs_url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wgs_contigs_url`, "EXPECTED_RESULT")
})
