# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsVirusPeptide")

model_instance <- V2reportsVirusPeptide$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("other_names", {
  # tests for the property `other_names` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`other_names`, "EXPECTED_RESULT")
})

test_that("nucleotide", {
  # tests for the property `nucleotide` (V2reportsSeqRangeSetFasta)

  # uncomment below to test the property
  #expect_equal(model.instance$`nucleotide`, "EXPECTED_RESULT")
})

test_that("protein", {
  # tests for the property `protein` (V2reportsSeqRangeSetFasta)

  # uncomment below to test the property
  #expect_equal(model.instance$`protein`, "EXPECTED_RESULT")
})

test_that("pdb_ids", {
  # tests for the property `pdb_ids` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`pdb_ids`, "EXPECTED_RESULT")
})

test_that("cdd", {
  # tests for the property `cdd` (array[V2reportsConservedDomain])

  # uncomment below to test the property
  #expect_equal(model.instance$`cdd`, "EXPECTED_RESULT")
})

test_that("uni_prot_kb", {
  # tests for the property `uni_prot_kb` (V2reportsVirusPeptideUniProtId)

  # uncomment below to test the property
  #expect_equal(model.instance$`uni_prot_kb`, "EXPECTED_RESULT")
})

test_that("mature_peptide", {
  # tests for the property `mature_peptide` (array[V2reportsVirusPeptide])

  # uncomment below to test the property
  #expect_equal(model.instance$`mature_peptide`, "EXPECTED_RESULT")
})

test_that("protein_completeness", {
  # tests for the property `protein_completeness` (V2reportsVirusPeptideViralPeptideCompleteness)

  # uncomment below to test the property
  #expect_equal(model.instance$`protein_completeness`, "EXPECTED_RESULT")
})
