# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsVirusAnnotationReport")

model_instance <- V2reportsVirusAnnotationReport$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("isolate_name", {
  # tests for the property `isolate_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isolate_name`, "EXPECTED_RESULT")
})

test_that("genes", {
  # tests for the property `genes` (array[V2reportsVirusGene])

  # uncomment below to test the property
  #expect_equal(model.instance$`genes`, "EXPECTED_RESULT")
})
