# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsReference")

model_instance <- V2reportsReference$new()

test_that("pmids", {
  # tests for the property `pmids` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`pmids`, "EXPECTED_RESULT")
})
