# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2AssemblyRevisionHistory")

model_instance <- V2AssemblyRevisionHistory$new()

test_that("assembly_revisions", {
  # tests for the property `assembly_revisions` (array[V2reportsAssemblyRevision])

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_revisions`, "EXPECTED_RESULT")
})

test_that("total_count", {
  # tests for the property `total_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_count`, "EXPECTED_RESULT")
})
