# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsCheckM")

model_instance <- V2reportsCheckM$new()

test_that("checkm_marker_set", {
  # tests for the property `checkm_marker_set` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`checkm_marker_set`, "EXPECTED_RESULT")
})

test_that("checkm_species_tax_id", {
  # tests for the property `checkm_species_tax_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`checkm_species_tax_id`, "EXPECTED_RESULT")
})

test_that("checkm_marker_set_rank", {
  # tests for the property `checkm_marker_set_rank` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`checkm_marker_set_rank`, "EXPECTED_RESULT")
})

test_that("checkm_version", {
  # tests for the property `checkm_version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`checkm_version`, "EXPECTED_RESULT")
})

test_that("completeness", {
  # tests for the property `completeness` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`completeness`, "EXPECTED_RESULT")
})

test_that("contamination", {
  # tests for the property `contamination` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`contamination`, "EXPECTED_RESULT")
})

test_that("completeness_percentile", {
  # tests for the property `completeness_percentile` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`completeness_percentile`, "EXPECTED_RESULT")
})
