# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsBioSampleId")

model_instance <- V2reportsBioSampleId$new()

test_that("db", {
  # tests for the property `db` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`db`, "EXPECTED_RESULT")
})

test_that("label", {
  # tests for the property `label` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`label`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})
