# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsTaxonomyTypeMaterial")

model_instance <- V2reportsTaxonomyTypeMaterial$new()

test_that("type_strain_name", {
  # tests for the property `type_strain_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type_strain_name`, "EXPECTED_RESULT")
})

test_that("type_strain_id", {
  # tests for the property `type_strain_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type_strain_id`, "EXPECTED_RESULT")
})

test_that("bio_collection_id", {
  # tests for the property `bio_collection_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`bio_collection_id`, "EXPECTED_RESULT")
})

test_that("bio_collection_name", {
  # tests for the property `bio_collection_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`bio_collection_name`, "EXPECTED_RESULT")
})

test_that("collection_type", {
  # tests for the property `collection_type` (array[V2reportsCollectionType])

  # uncomment below to test the property
  #expect_equal(model.instance$`collection_type`, "EXPECTED_RESULT")
})

test_that("type_class", {
  # tests for the property `type_class` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type_class`, "EXPECTED_RESULT")
})
