# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsTaxonomyNamesReportMatch")

model_instance <- V2reportsTaxonomyNamesReportMatch$new()

test_that("taxonomy", {
  # tests for the property `taxonomy` (V2reportsTaxonomyNamesDescriptor)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxonomy`, "EXPECTED_RESULT")
})

test_that("query", {
  # tests for the property `query` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`query`, "EXPECTED_RESULT")
})

test_that("warning", {
  # tests for the property `warning` (V2reportsWarning)

  # uncomment below to test the property
  #expect_equal(model.instance$`warning`, "EXPECTED_RESULT")
})

test_that("errors", {
  # tests for the property `errors` (array[V2reportsError])

  # uncomment below to test the property
  #expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})
