# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2GeneLinksReplyGeneLink")

model_instance <- V2GeneLinksReplyGeneLink$new()

test_that("gene_id", {
  # tests for the property `gene_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_id`, "EXPECTED_RESULT")
})

test_that("gene_link_type", {
  # tests for the property `gene_link_type` (V2GeneLinksReplyGeneLinkType)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_link_type`, "EXPECTED_RESULT")
})

test_that("resource_link", {
  # tests for the property `resource_link` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`resource_link`, "EXPECTED_RESULT")
})

test_that("resource_id", {
  # tests for the property `resource_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`resource_id`, "EXPECTED_RESULT")
})
