# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyLinksResponse")

model_instance <- V2TaxonomyLinksResponse$new()

test_that("tax_id", {
  # tests for the property `tax_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_id`, "EXPECTED_RESULT")
})

test_that("encyclopedia_of_life", {
  # tests for the property `encyclopedia_of_life` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`encyclopedia_of_life`, "EXPECTED_RESULT")
})

test_that("global_biodiversity_information_facility", {
  # tests for the property `global_biodiversity_information_facility` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`global_biodiversity_information_facility`, "EXPECTED_RESULT")
})

test_that("inaturalist", {
  # tests for the property `inaturalist` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`inaturalist`, "EXPECTED_RESULT")
})

test_that("viralzone", {
  # tests for the property `viralzone` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`viralzone`, "EXPECTED_RESULT")
})

test_that("wikipedia", {
  # tests for the property `wikipedia` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wikipedia`, "EXPECTED_RESULT")
})

test_that("generic_links", {
  # tests for the property `generic_links` (array[V2TaxonomyLinksResponseGenericLink])

  # uncomment below to test the property
  #expect_equal(model.instance$`generic_links`, "EXPECTED_RESULT")
})
