# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsGenomeAnnotation")

model_instance <- V2reportsGenomeAnnotation$new()

test_that("gene_id", {
  # tests for the property `gene_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_id`, "EXPECTED_RESULT")
})

test_that("symbol", {
  # tests for the property `symbol` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`symbol`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("tax_id", {
  # tests for the property `tax_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_id`, "EXPECTED_RESULT")
})

test_that("taxname", {
  # tests for the property `taxname` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxname`, "EXPECTED_RESULT")
})

test_that("common_name", {
  # tests for the property `common_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`common_name`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (V2reportsGeneType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("gene_type", {
  # tests for the property `gene_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_type`, "EXPECTED_RESULT")
})

test_that("rna_type", {
  # tests for the property `rna_type` (V2reportsRnaType)

  # uncomment below to test the property
  #expect_equal(model.instance$`rna_type`, "EXPECTED_RESULT")
})

test_that("orientation", {
  # tests for the property `orientation` (V2reportsOrientation)

  # uncomment below to test the property
  #expect_equal(model.instance$`orientation`, "EXPECTED_RESULT")
})

test_that("locus_tag", {
  # tests for the property `locus_tag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`locus_tag`, "EXPECTED_RESULT")
})

test_that("reference_standards", {
  # tests for the property `reference_standards` (array[V2reportsGenomicRegion])

  # uncomment below to test the property
  #expect_equal(model.instance$`reference_standards`, "EXPECTED_RESULT")
})

test_that("genomic_regions", {
  # tests for the property `genomic_regions` (array[V2reportsGenomicRegion])

  # uncomment below to test the property
  #expect_equal(model.instance$`genomic_regions`, "EXPECTED_RESULT")
})

test_that("transcripts", {
  # tests for the property `transcripts` (array[V2reportsTranscript])

  # uncomment below to test the property
  #expect_equal(model.instance$`transcripts`, "EXPECTED_RESULT")
})

test_that("proteins", {
  # tests for the property `proteins` (array[V2reportsProtein])

  # uncomment below to test the property
  #expect_equal(model.instance$`proteins`, "EXPECTED_RESULT")
})

test_that("chromosomes", {
  # tests for the property `chromosomes` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`chromosomes`, "EXPECTED_RESULT")
})

test_that("swiss_prot_accessions", {
  # tests for the property `swiss_prot_accessions` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`swiss_prot_accessions`, "EXPECTED_RESULT")
})

test_that("ensembl_gene_ids", {
  # tests for the property `ensembl_gene_ids` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`ensembl_gene_ids`, "EXPECTED_RESULT")
})

test_that("omim_ids", {
  # tests for the property `omim_ids` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`omim_ids`, "EXPECTED_RESULT")
})

test_that("synonyms", {
  # tests for the property `synonyms` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`synonyms`, "EXPECTED_RESULT")
})

test_that("annotations", {
  # tests for the property `annotations` (array[V2reportsAnnotation])

  # uncomment below to test the property
  #expect_equal(model.instance$`annotations`, "EXPECTED_RESULT")
})
