# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsGenomicLocation")

model_instance <- V2reportsGenomicLocation$new()

test_that("genomic_accession_version", {
  # tests for the property `genomic_accession_version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`genomic_accession_version`, "EXPECTED_RESULT")
})

test_that("sequence_name", {
  # tests for the property `sequence_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequence_name`, "EXPECTED_RESULT")
})

test_that("genomic_range", {
  # tests for the property `genomic_range` (V2reportsRange)

  # uncomment below to test the property
  #expect_equal(model.instance$`genomic_range`, "EXPECTED_RESULT")
})

test_that("exons", {
  # tests for the property `exons` (array[V2reportsRange])

  # uncomment below to test the property
  #expect_equal(model.instance$`exons`, "EXPECTED_RESULT")
})
