# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsGeneDescriptor")

model_instance <- V2reportsGeneDescriptor$new()

test_that("gene_id", {
  # tests for the property `gene_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_id`, "EXPECTED_RESULT")
})

test_that("symbol", {
  # tests for the property `symbol` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`symbol`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("tax_id", {
  # tests for the property `tax_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_id`, "EXPECTED_RESULT")
})

test_that("taxname", {
  # tests for the property `taxname` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxname`, "EXPECTED_RESULT")
})

test_that("common_name", {
  # tests for the property `common_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`common_name`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (V2reportsGeneType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})

test_that("rna_type", {
  # tests for the property `rna_type` (V2reportsRnaType)

  # uncomment below to test the property
  #expect_equal(model.instance$`rna_type`, "EXPECTED_RESULT")
})

test_that("orientation", {
  # tests for the property `orientation` (V2reportsOrientation)

  # uncomment below to test the property
  #expect_equal(model.instance$`orientation`, "EXPECTED_RESULT")
})

test_that("reference_standards", {
  # tests for the property `reference_standards` (array[V2reportsGenomicRegion])

  # uncomment below to test the property
  #expect_equal(model.instance$`reference_standards`, "EXPECTED_RESULT")
})

test_that("genomic_regions", {
  # tests for the property `genomic_regions` (array[V2reportsGenomicRegion])

  # uncomment below to test the property
  #expect_equal(model.instance$`genomic_regions`, "EXPECTED_RESULT")
})

test_that("chromosomes", {
  # tests for the property `chromosomes` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`chromosomes`, "EXPECTED_RESULT")
})

test_that("nomenclature_authority", {
  # tests for the property `nomenclature_authority` (V2reportsNomenclatureAuthority)

  # uncomment below to test the property
  #expect_equal(model.instance$`nomenclature_authority`, "EXPECTED_RESULT")
})

test_that("swiss_prot_accessions", {
  # tests for the property `swiss_prot_accessions` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`swiss_prot_accessions`, "EXPECTED_RESULT")
})

test_that("ensembl_gene_ids", {
  # tests for the property `ensembl_gene_ids` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`ensembl_gene_ids`, "EXPECTED_RESULT")
})

test_that("omim_ids", {
  # tests for the property `omim_ids` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`omim_ids`, "EXPECTED_RESULT")
})

test_that("synonyms", {
  # tests for the property `synonyms` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`synonyms`, "EXPECTED_RESULT")
})

test_that("replaced_gene_id", {
  # tests for the property `replaced_gene_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`replaced_gene_id`, "EXPECTED_RESULT")
})

test_that("annotations", {
  # tests for the property `annotations` (array[V2reportsAnnotation])

  # uncomment below to test the property
  #expect_equal(model.instance$`annotations`, "EXPECTED_RESULT")
})

test_that("transcript_count", {
  # tests for the property `transcript_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`transcript_count`, "EXPECTED_RESULT")
})

test_that("protein_count", {
  # tests for the property `protein_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`protein_count`, "EXPECTED_RESULT")
})

test_that("transcript_type_counts", {
  # tests for the property `transcript_type_counts` (array[V2reportsTranscriptTypeCount])

  # uncomment below to test the property
  #expect_equal(model.instance$`transcript_type_counts`, "EXPECTED_RESULT")
})

test_that("gene_groups", {
  # tests for the property `gene_groups` (array[V2reportsGeneGroup])

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_groups`, "EXPECTED_RESULT")
})

test_that("summary", {
  # tests for the property `summary` (array[V2reportsGeneSummary])

  # uncomment below to test the property
  #expect_equal(model.instance$`summary`, "EXPECTED_RESULT")
})

test_that("gene_ontology", {
  # tests for the property `gene_ontology` (V2reportsGeneOntology)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_ontology`, "EXPECTED_RESULT")
})

test_that("locus_tag", {
  # tests for the property `locus_tag` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`locus_tag`, "EXPECTED_RESULT")
})
