# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsMessage")

model_instance <- V2reportsMessage$new()

test_that("error", {
  # tests for the property `error` (V2reportsError)

  # uncomment below to test the property
  #expect_equal(model.instance$`error`, "EXPECTED_RESULT")
})

test_that("warning", {
  # tests for the property `warning` (V2reportsWarning)

  # uncomment below to test the property
  #expect_equal(model.instance$`warning`, "EXPECTED_RESULT")
})
