# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2GenePubmedIdsResponse")

model_instance <- V2GenePubmedIdsResponse$new()

test_that("pubmedIds", {
  # tests for the property `pubmedIds` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`pubmedIds`, "EXPECTED_RESULT")
})
