# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2SciNameAndIds")

model_instance <- V2SciNameAndIds$new()

test_that("sci_name_and_ids", {
  # tests for the property `sci_name_and_ids` (array[V2SciNameAndIdsSciNameAndId])

  # uncomment below to test the property
  #expect_equal(model.instance$`sci_name_and_ids`, "EXPECTED_RESULT")
})
