# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TabularOutput")

model_instance <- V2TabularOutput$new()

test_that("data", {
  # tests for the property `data` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})
