# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2SleepReply")

model_instance <- V2SleepReply$new()

test_that("reply", {
  # tests for the property `reply` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`reply`, "EXPECTED_RESULT")
})
