# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsOrganism")

model_instance <- V2reportsOrganism$new()

test_that("tax_id", {
  # tests for the property `tax_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_id`, "EXPECTED_RESULT")
})

test_that("sci_name", {
  # tests for the property `sci_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sci_name`, "EXPECTED_RESULT")
})

test_that("organism_name", {
  # tests for the property `organism_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`organism_name`, "EXPECTED_RESULT")
})

test_that("common_name", {
  # tests for the property `common_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`common_name`, "EXPECTED_RESULT")
})

test_that("lineage", {
  # tests for the property `lineage` (array[V2reportsLineageOrganism])

  # uncomment below to test the property
  #expect_equal(model.instance$`lineage`, "EXPECTED_RESULT")
})

test_that("strain", {
  # tests for the property `strain` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`strain`, "EXPECTED_RESULT")
})

test_that("pangolin_classification", {
  # tests for the property `pangolin_classification` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`pangolin_classification`, "EXPECTED_RESULT")
})

test_that("infraspecific_names", {
  # tests for the property `infraspecific_names` (V2reportsInfraspecificNames)

  # uncomment below to test the property
  #expect_equal(model.instance$`infraspecific_names`, "EXPECTED_RESULT")
})
