# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsGenomicRegion")

model_instance <- V2reportsGenomicRegion$new()

test_that("gene_range", {
  # tests for the property `gene_range` (V2reportsSeqRangeSet)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_range`, "EXPECTED_RESULT")
})

test_that("type", {
  # tests for the property `type` (V2reportsGenomicRegionGenomicRegionType)

  # uncomment below to test the property
  #expect_equal(model.instance$`type`, "EXPECTED_RESULT")
})
