# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2SeqRange")

model_instance <- V2SeqRange$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("begin", {
  # tests for the property `begin` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`begin`, "EXPECTED_RESULT")
})

test_that("end", {
  # tests for the property `end` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`end`, "EXPECTED_RESULT")
})

test_that("orientation", {
  # tests for the property `orientation` (V2reportsOrientation)

  # uncomment below to test the property
  #expect_equal(model.instance$`orientation`, "EXPECTED_RESULT")
})
