# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyFilteredSubtreeResponseEdgesEntry")

model_instance <- V2TaxonomyFilteredSubtreeResponseEdgesEntry$new()

test_that("default", {
  # tests for the property `default` (V2TaxonomyFilteredSubtreeResponseEdge)

  # uncomment below to test the property
  #expect_equal(model.instance$`default`, "EXPECTED_RESULT")
})
