# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsVirusGene")

model_instance <- V2reportsVirusGene$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("gene_id", {
  # tests for the property `gene_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_id`, "EXPECTED_RESULT")
})

test_that("nucleotide", {
  # tests for the property `nucleotide` (V2reportsSeqRangeSetFasta)

  # uncomment below to test the property
  #expect_equal(model.instance$`nucleotide`, "EXPECTED_RESULT")
})

test_that("cds", {
  # tests for the property `cds` (array[V2reportsVirusPeptide])

  # uncomment below to test the property
  #expect_equal(model.instance$`cds`, "EXPECTED_RESULT")
})
