# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2DownloadSummaryFileSummary")

model_instance <- V2DownloadSummaryFileSummary$new()

test_that("file_count", {
  # tests for the property `file_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`file_count`, "EXPECTED_RESULT")
})

test_that("size_mb", {
  # tests for the property `size_mb` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`size_mb`, "EXPECTED_RESULT")
})
