# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2SciNameAndIdsSciNameAndId")

model_instance <- V2SciNameAndIdsSciNameAndId$new()

test_that("sci_name", {
  # tests for the property `sci_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sci_name`, "EXPECTED_RESULT")
})

test_that("tax_id", {
  # tests for the property `tax_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_id`, "EXPECTED_RESULT")
})

test_that("common_name", {
  # tests for the property `common_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`common_name`, "EXPECTED_RESULT")
})

test_that("matched_term", {
  # tests for the property `matched_term` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`matched_term`, "EXPECTED_RESULT")
})

test_that("rank", {
  # tests for the property `rank` (V2reportsRankType)

  # uncomment below to test the property
  #expect_equal(model.instance$`rank`, "EXPECTED_RESULT")
})

test_that("group_name", {
  # tests for the property `group_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`group_name`, "EXPECTED_RESULT")
})
