# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2AssemblyLinksReplyAssemblyLink")

model_instance <- V2AssemblyLinksReplyAssemblyLink$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("assembly_link_type", {
  # tests for the property `assembly_link_type` (V2AssemblyLinksReplyAssemblyLinkType)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_link_type`, "EXPECTED_RESULT")
})

test_that("resource_link", {
  # tests for the property `resource_link` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`resource_link`, "EXPECTED_RESULT")
})

test_that("linked_identifiers", {
  # tests for the property `linked_identifiers` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`linked_identifiers`, "EXPECTED_RESULT")
})
