# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsGeneGroup")

model_instance <- V2reportsGeneGroup$new()

test_that("id", {
  # tests for the property `id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

test_that("method", {
  # tests for the property `method` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`method`, "EXPECTED_RESULT")
})
