# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsSeqRangeSet")

model_instance <- V2reportsSeqRangeSet$new()

test_that("accession_version", {
  # tests for the property `accession_version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession_version`, "EXPECTED_RESULT")
})

test_that("range", {
  # tests for the property `range` (array[V2reportsRange])

  # uncomment below to test the property
  #expect_equal(model.instance$`range`, "EXPECTED_RESULT")
})
