# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsOrganelleGeneCounts")

model_instance <- V2reportsOrganelleGeneCounts$new()

test_that("total", {
  # tests for the property `total` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("protein_coding", {
  # tests for the property `protein_coding` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`protein_coding`, "EXPECTED_RESULT")
})

test_that("rrna", {
  # tests for the property `rrna` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`rrna`, "EXPECTED_RESULT")
})

test_that("trna", {
  # tests for the property `trna` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`trna`, "EXPECTED_RESULT")
})

test_that("lncrna", {
  # tests for the property `lncrna` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`lncrna`, "EXPECTED_RESULT")
})
