# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsMaturePeptide")

model_instance <- V2reportsMaturePeptide$new()

test_that("accession_version", {
  # tests for the property `accession_version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession_version`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("length", {
  # tests for the property `length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`length`, "EXPECTED_RESULT")
})
