# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyNode")

model_instance <- V2TaxonomyNode$new()

test_that("tax_id", {
  # tests for the property `tax_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_id`, "EXPECTED_RESULT")
})

test_that("organism_name", {
  # tests for the property `organism_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`organism_name`, "EXPECTED_RESULT")
})

test_that("common_name", {
  # tests for the property `common_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`common_name`, "EXPECTED_RESULT")
})

test_that("genbank_common_name", {
  # tests for the property `genbank_common_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`genbank_common_name`, "EXPECTED_RESULT")
})

test_that("acronyms", {
  # tests for the property `acronyms` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`acronyms`, "EXPECTED_RESULT")
})

test_that("genbank_acronym", {
  # tests for the property `genbank_acronym` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`genbank_acronym`, "EXPECTED_RESULT")
})

test_that("blast_name", {
  # tests for the property `blast_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`blast_name`, "EXPECTED_RESULT")
})

test_that("lineage", {
  # tests for the property `lineage` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`lineage`, "EXPECTED_RESULT")
})

test_that("children", {
  # tests for the property `children` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`children`, "EXPECTED_RESULT")
})

test_that("descendent_with_described_species_names_count", {
  # tests for the property `descendent_with_described_species_names_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`descendent_with_described_species_names_count`, "EXPECTED_RESULT")
})

test_that("rank", {
  # tests for the property `rank` (V2reportsRankType)

  # uncomment below to test the property
  #expect_equal(model.instance$`rank`, "EXPECTED_RESULT")
})

test_that("has_described_species_name", {
  # tests for the property `has_described_species_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`has_described_species_name`, "EXPECTED_RESULT")
})

test_that("counts", {
  # tests for the property `counts` (array[V2TaxonomyNodeCountByType])

  # uncomment below to test the property
  #expect_equal(model.instance$`counts`, "EXPECTED_RESULT")
})

test_that("min_ord", {
  # tests for the property `min_ord` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`min_ord`, "EXPECTED_RESULT")
})

test_that("max_ord", {
  # tests for the property `max_ord` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`max_ord`, "EXPECTED_RESULT")
})

test_that("extinct", {
  # tests for the property `extinct` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`extinct`, "EXPECTED_RESULT")
})

test_that("genomic_moltype", {
  # tests for the property `genomic_moltype` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`genomic_moltype`, "EXPECTED_RESULT")
})
