# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsWarningReplacedId")

model_instance <- V2reportsWarningReplacedId$new()

test_that("requested", {
  # tests for the property `requested` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`requested`, "EXPECTED_RESULT")
})

test_that("returned", {
  # tests for the property `returned` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`returned`, "EXPECTED_RESULT")
})
