# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2GenomeAnnotationTableSummaryReply")

model_instance <- V2GenomeAnnotationTableSummaryReply$new()

test_that("accession", {
  # tests for the property `accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession`, "EXPECTED_RESULT")
})

test_that("chromosomes", {
  # tests for the property `chromosomes` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`chromosomes`, "EXPECTED_RESULT")
})

test_that("gene_types", {
  # tests for the property `gene_types` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_types`, "EXPECTED_RESULT")
})

test_that("empty_columns", {
  # tests for the property `empty_columns` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`empty_columns`, "EXPECTED_RESULT")
})
