# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ProkaryoteApi")

api_instance <- ProkaryoteApi$new()

test_that("DownloadProkaryoteGenePackage", {
  # tests for DownloadProkaryoteGenePackage
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get a prokaryote gene dataset by RefSeq protein accession
  # Get a prokaryote gene dataset including gene and protein fasta sequence, annotation and metadata by prokaryote protein accession.
  # @param accessions array[character] WP prokaryote protein accession
  # @param include_annotation_type array[V2Fasta] Select additional types of annotation to include in the data package.  If unset, no annotation is provided. (optional)
  # @param gene_flank_config_length integer  (optional)
  # @param taxon character NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank When specified, return data from this taxon and its subtree (optional)
  # @param filename character Output file name. (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DownloadProkaryoteGenePackagePost", {
  # tests for DownloadProkaryoteGenePackagePost
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get a prokaryote gene dataset by RefSeq protein accession by POST
  # Get a prokaryote gene dataset including gene and protein fasta sequence, annotation and metadata by prokaryote protein accession by POST.
  # @param v2_prokaryote_gene_request V2ProkaryoteGeneRequest 
  # @param filename character Output file name. (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
