# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2GeneChromosomeSummaryReply")

model_instance <- V2GeneChromosomeSummaryReply$new()

test_that("gene_chromosome_summaries", {
  # tests for the property `gene_chromosome_summaries` (array[V2GeneChromosomeSummaryReplyGeneChromosomeSummary])

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_chromosome_summaries`, "EXPECTED_RESULT")
})
