# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2AssemblyLinksReply")

model_instance <- V2AssemblyLinksReply$new()

test_that("assembly_links", {
  # tests for the property `assembly_links` (array[V2AssemblyLinksReplyAssemblyLink])

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_links`, "EXPECTED_RESULT")
})
