# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsTaxonomyNode")

model_instance <- V2reportsTaxonomyNode$new()

test_that("tax_id", {
  # tests for the property `tax_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_id`, "EXPECTED_RESULT")
})

test_that("rank", {
  # tests for the property `rank` (V2reportsRankType)

  # uncomment below to test the property
  #expect_equal(model.instance$`rank`, "EXPECTED_RESULT")
})

test_that("current_scientific_name", {
  # tests for the property `current_scientific_name` (V2reportsNameAndAuthority)

  # uncomment below to test the property
  #expect_equal(model.instance$`current_scientific_name`, "EXPECTED_RESULT")
})

test_that("basionym", {
  # tests for the property `basionym` (V2reportsNameAndAuthority)

  # uncomment below to test the property
  #expect_equal(model.instance$`basionym`, "EXPECTED_RESULT")
})

test_that("curator_common_name", {
  # tests for the property `curator_common_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`curator_common_name`, "EXPECTED_RESULT")
})

test_that("group_name", {
  # tests for the property `group_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`group_name`, "EXPECTED_RESULT")
})

test_that("has_type_material", {
  # tests for the property `has_type_material` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`has_type_material`, "EXPECTED_RESULT")
})

test_that("classification", {
  # tests for the property `classification` (V2reportsClassification)

  # uncomment below to test the property
  #expect_equal(model.instance$`classification`, "EXPECTED_RESULT")
})

test_that("parents", {
  # tests for the property `parents` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`parents`, "EXPECTED_RESULT")
})

test_that("children", {
  # tests for the property `children` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`children`, "EXPECTED_RESULT")
})

test_that("counts", {
  # tests for the property `counts` (array[V2reportsTaxonomyNodeCountByType])

  # uncomment below to test the property
  #expect_equal(model.instance$`counts`, "EXPECTED_RESULT")
})

test_that("genomic_moltype", {
  # tests for the property `genomic_moltype` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`genomic_moltype`, "EXPECTED_RESULT")
})

test_that("current_scientific_name_is_formal", {
  # tests for the property `current_scientific_name_is_formal` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`current_scientific_name_is_formal`, "EXPECTED_RESULT")
})

test_that("secondary_tax_ids", {
  # tests for the property `secondary_tax_ids` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`secondary_tax_ids`, "EXPECTED_RESULT")
})
