# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2OrthologRequest")

model_instance <- V2OrthologRequest$new()

test_that("gene_id", {
  # tests for the property `gene_id` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_id`, "EXPECTED_RESULT")
})

test_that("returned_content", {
  # tests for the property `returned_content` (V2OrthologRequestContentType)

  # uncomment below to test the property
  #expect_equal(model.instance$`returned_content`, "EXPECTED_RESULT")
})

test_that("taxon_filter", {
  # tests for the property `taxon_filter` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon_filter`, "EXPECTED_RESULT")
})

test_that("page_size", {
  # tests for the property `page_size` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`page_size`, "EXPECTED_RESULT")
})

test_that("page_token", {
  # tests for the property `page_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`page_token`, "EXPECTED_RESULT")
})
