# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2OrganismQueryRequest")

model_instance <- V2OrganismQueryRequest$new()

test_that("organism_query", {
  # tests for the property `organism_query` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`organism_query`, "EXPECTED_RESULT")
})

test_that("taxon_query", {
  # tests for the property `taxon_query` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon_query`, "EXPECTED_RESULT")
})

test_that("tax_rank_filter", {
  # tests for the property `tax_rank_filter` (V2OrganismQueryRequestTaxRankFilter)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_rank_filter`, "EXPECTED_RESULT")
})

test_that("taxon_resource_filter", {
  # tests for the property `taxon_resource_filter` (V2OrganismQueryRequestTaxonResourceFilter)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon_resource_filter`, "EXPECTED_RESULT")
})

test_that("exact_match", {
  # tests for the property `exact_match` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`exact_match`, "EXPECTED_RESULT")
})
