# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsAtypicalInfo")

model_instance <- V2reportsAtypicalInfo$new()

test_that("is_atypical", {
  # tests for the property `is_atypical` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`is_atypical`, "EXPECTED_RESULT")
})

test_that("warnings", {
  # tests for the property `warnings` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`warnings`, "EXPECTED_RESULT")
})
