# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2GeneChromosomeSummaryRequest")

model_instance <- V2GeneChromosomeSummaryRequest$new()

test_that("taxon", {
  # tests for the property `taxon` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`taxon`, "EXPECTED_RESULT")
})

test_that("annotation_name", {
  # tests for the property `annotation_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`annotation_name`, "EXPECTED_RESULT")
})
