# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsBioSampleOwner")

model_instance <- V2reportsBioSampleOwner$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("contacts", {
  # tests for the property `contacts` (array[V2reportsBioSampleContact])

  # uncomment below to test the property
  #expect_equal(model.instance$`contacts`, "EXPECTED_RESULT")
})
