# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsTypeMaterial")

model_instance <- V2reportsTypeMaterial$new()

test_that("type_label", {
  # tests for the property `type_label` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type_label`, "EXPECTED_RESULT")
})

test_that("type_display_text", {
  # tests for the property `type_display_text` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`type_display_text`, "EXPECTED_RESULT")
})
