# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2VersionReply")

model_instance <- V2VersionReply$new()

test_that("version", {
  # tests for the property `version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`version`, "EXPECTED_RESULT")
})

test_that("major_ver", {
  # tests for the property `major_ver` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`major_ver`, "EXPECTED_RESULT")
})

test_that("minor_ver", {
  # tests for the property `minor_ver` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`minor_ver`, "EXPECTED_RESULT")
})

test_that("patch_ver", {
  # tests for the property `patch_ver` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`patch_ver`, "EXPECTED_RESULT")
})
