# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsOrganelleInfo")

model_instance <- V2reportsOrganelleInfo$new()

test_that("assembly_name", {
  # tests for the property `assembly_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_name`, "EXPECTED_RESULT")
})

test_that("infraspecific_name", {
  # tests for the property `infraspecific_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`infraspecific_name`, "EXPECTED_RESULT")
})

test_that("bioproject", {
  # tests for the property `bioproject` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`bioproject`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("total_seq_length", {
  # tests for the property `total_seq_length` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`total_seq_length`, "EXPECTED_RESULT")
})

test_that("submitter", {
  # tests for the property `submitter` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`submitter`, "EXPECTED_RESULT")
})
