# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsGenomeAnnotationReportMatch")

model_instance <- V2reportsGenomeAnnotationReportMatch$new()

test_that("annotation", {
  # tests for the property `annotation` (V2reportsGenomeAnnotation)

  # uncomment below to test the property
  #expect_equal(model.instance$`annotation`, "EXPECTED_RESULT")
})

test_that("query", {
  # tests for the property `query` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`query`, "EXPECTED_RESULT")
})

test_that("warning", {
  # tests for the property `warning` (V2reportsWarning)

  # uncomment below to test the property
  #expect_equal(model.instance$`warning`, "EXPECTED_RESULT")
})

test_that("errors", {
  # tests for the property `errors` (array[V2reportsError])

  # uncomment below to test the property
  #expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})

test_that("row_id", {
  # tests for the property `row_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`row_id`, "EXPECTED_RESULT")
})
