# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2SortField")

model_instance <- V2SortField$new()

test_that("field", {
  # tests for the property `field` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`field`, "EXPECTED_RESULT")
})

test_that("direction", {
  # tests for the property `direction` (V2SortDirection)

  # uncomment below to test the property
  #expect_equal(model.instance$`direction`, "EXPECTED_RESULT")
})
