# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsGeneSummary")

model_instance <- V2reportsGeneSummary$new()

test_that("source", {
  # tests for the property `source` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`source`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("date", {
  # tests for the property `date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`date`, "EXPECTED_RESULT")
})
