# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsSeqRangeSetFasta")

model_instance <- V2reportsSeqRangeSetFasta$new()

test_that("seq_id", {
  # tests for the property `seq_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`seq_id`, "EXPECTED_RESULT")
})

test_that("accession_version", {
  # tests for the property `accession_version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession_version`, "EXPECTED_RESULT")
})

test_that("title", {
  # tests for the property `title` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`title`, "EXPECTED_RESULT")
})

test_that("sequence_hash", {
  # tests for the property `sequence_hash` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequence_hash`, "EXPECTED_RESULT")
})

test_that("range", {
  # tests for the property `range` (array[V2reportsRange])

  # uncomment below to test the property
  #expect_equal(model.instance$`range`, "EXPECTED_RESULT")
})
