# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsOrganelle")

model_instance <- V2reportsOrganelle$new()

test_that("description", {
  # tests for the property `description` (V2reportsOrganelleType)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("genbank", {
  # tests for the property `genbank` (V2reportsSequenceInformation)

  # uncomment below to test the property
  #expect_equal(model.instance$`genbank`, "EXPECTED_RESULT")
})

test_that("refseq", {
  # tests for the property `refseq` (V2reportsSequenceInformation)

  # uncomment below to test the property
  #expect_equal(model.instance$`refseq`, "EXPECTED_RESULT")
})

test_that("organism", {
  # tests for the property `organism` (V2reportsOrganism)

  # uncomment below to test the property
  #expect_equal(model.instance$`organism`, "EXPECTED_RESULT")
})

test_that("bioprojects", {
  # tests for the property `bioprojects` (array[V2reportsBioProject])

  # uncomment below to test the property
  #expect_equal(model.instance$`bioprojects`, "EXPECTED_RESULT")
})

test_that("biosample", {
  # tests for the property `biosample` (V2reportsOrganelleBiosample)

  # uncomment below to test the property
  #expect_equal(model.instance$`biosample`, "EXPECTED_RESULT")
})

test_that("gene_counts", {
  # tests for the property `gene_counts` (V2reportsOrganelleGeneCounts)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_counts`, "EXPECTED_RESULT")
})

test_that("length", {
  # tests for the property `length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`length`, "EXPECTED_RESULT")
})

test_that("topology", {
  # tests for the property `topology` (V2reportsOrganelleTopology)

  # uncomment below to test the property
  #expect_equal(model.instance$`topology`, "EXPECTED_RESULT")
})

test_that("gene_count", {
  # tests for the property `gene_count` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_count`, "EXPECTED_RESULT")
})
