# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test VirusApi")

api_instance <- VirusApi$new()

test_that("Sars2ProteinDownload", {
  # tests for Sars2ProteinDownload
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Download SARS-CoV-2 protein and CDS datasets by protein name
  # Download SARS-CoV-2 protein datasets
  # @param proteins array[character] Which proteins to retrieve in the data package
  # @param refseq_only character If true, limit results to RefSeq genomes. (optional)
  # @param annotated_only character If true, limit results to annotated genomes. (optional)
  # @param released_since character If set, limit results to viral genomes that have been released after a specified date (and optionally, time). April 1, 2020 midnight UTC should be formatted as '2020-04-01T00:00:00.000Z' (optional)
  # @param updated_since character  (optional)
  # @param host character If set, limit results to genomes extracted from this host (Taxonomy ID or name) All hosts by default (optional)
  # @param pangolin_classification character If set, limit results to genomes classified to this lineage by the PangoLearn tool. (optional)
  # @param geo_location character Assemblies from this location (country or continent) (optional)
  # @param usa_state character Assemblies from this state (official two letter code only) (optional)
  # @param complete_only character only include complete genomes. (optional)
  # @param include_sequence array[V2ViralSequenceType] Specify which sequence files to include in the download (optional)
  # @param aux_report array[V2VirusDatasetReportType] List additional reports to include with download. Data report is included by default. (optional)
  # @param filename character Output file name. (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Sars2ProteinDownloadPost", {
  # tests for Sars2ProteinDownloadPost
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Download SARS-CoV-2 protein and CDS datasets by protein name by POST request
  # Download SARS-CoV-2 protein datasets POST request
  # @param v2_sars2_protein_dataset_request V2Sars2ProteinDatasetRequest 
  # @param filename character Output file name. (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Sars2ProteinSummary", {
  # tests for Sars2ProteinSummary
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Summary of SARS-CoV-2 protein and CDS datasets by protein name
  # Download a summary of available SARS-CoV-2 protein datasets
  # @param proteins array[character] Which proteins to retrieve in the data package
  # @param refseq_only character If true, limit results to RefSeq genomes. (optional)
  # @param annotated_only character If true, limit results to annotated genomes. (optional)
  # @param released_since character If set, limit results to viral genomes that have been released after a specified date (and optionally, time). April 1, 2020 midnight UTC should be formatted as '2020-04-01T00:00:00.000Z' (optional)
  # @param updated_since character  (optional)
  # @param host character If set, limit results to genomes extracted from this host (Taxonomy ID or name) All hosts by default (optional)
  # @param pangolin_classification character If set, limit results to genomes classified to this lineage by the PangoLearn tool. (optional)
  # @param geo_location character Assemblies from this location (country or continent) (optional)
  # @param usa_state character Assemblies from this state (official two letter code only) (optional)
  # @param complete_only character only include complete genomes. (optional)
  # @param include_sequence array[V2ViralSequenceType] Specify which sequence files to include in the download (optional)
  # @param aux_report array[V2VirusDatasetReportType] List additional reports to include with download. Data report is included by default. (optional)
  # @return [V2DownloadSummary]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Sars2ProteinSummaryByPost", {
  # tests for Sars2ProteinSummaryByPost
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Summary of SARS-CoV-2 protein and CDS datasets by protein name
  # Download a summary of available SARS-CoV-2 protein datasets
  # @param v2_sars2_protein_dataset_request V2Sars2ProteinDatasetRequest 
  # @return [V2DownloadSummary]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("Sars2ProteinTable", {
  # tests for Sars2ProteinTable
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get SARS-CoV-2 protein metadata in a tabular format.
  # Get protein metadata in tabular format for SARS-CoV-2 genomes.
  # @param proteins array[character] Which proteins to retrieve in the data package
  # @param refseq_only character If true, limit results to RefSeq genomes. (optional)
  # @param annotated_only character If true, limit results to annotated genomes. (optional)
  # @param released_since character If set, limit results to viral genomes that have been released after a specified date (and optionally, time). April 1, 2020 midnight UTC should be formatted as '2020-04-01T00:00:00.000Z' (optional)
  # @param updated_since character  (optional)
  # @param host character If set, limit results to genomes extracted from this host (Taxonomy ID or name) All hosts by default (optional)
  # @param pangolin_classification character If set, limit results to genomes classified to this lineage by the PangoLearn tool. (optional)
  # @param geo_location character Assemblies from this location (country or continent) (optional)
  # @param usa_state character Assemblies from this state (official two letter code only) (optional)
  # @param complete_only character only include complete genomes. (optional)
  # @param table_fields array[V2VirusTableField] Specify which fields to include in the tabular report (optional)
  # @param include_sequence array[V2ViralSequenceType] Specify which sequence files to include in the download (optional)
  # @param aux_report array[V2VirusDatasetReportType] List additional reports to include with download. Data report is included by default. (optional)
  # @param format V2TableFormat Choose download format (tsv, csv or jsonl) (optional)
  # @return [V2TabularOutput]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusAccessionAvailability", {
  # tests for VirusAccessionAvailability
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Check available viruses by accession
  # Check available viruses
  # @param accessions array[character] virus accessions
  # @return [V2VirusAvailability]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusAccessionAvailabilityPost", {
  # tests for VirusAccessionAvailabilityPost
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Check available viruses by accession
  # Check available viruses
  # @param v2_virus_availability_request V2VirusAvailabilityRequest 
  # @return [V2VirusAvailability]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusAnnotationReportsByAcessions", {
  # tests for VirusAnnotationReportsByAcessions
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get virus annotation report by accession
  # Get virus annotation report by accesion. By default, in paged JSON format, but also available as tabular (accept: text/tab-separated-values) or json-lines (accept: application/x-ndjson)
  # @param accessions array[character] genome sequence accessions
  # @param filter_refseq_only character If true, limit results to RefSeq genomes. (optional)
  # @param filter_annotated_only character If true, limit results to annotated genomes. (optional)
  # @param filter_released_since character If set, limit results to viral genomes that have been released after a specified date (and optionally, time). April 1, 2020 midnight UTC should be formatted as '2020-04-01T00:00:00.000Z' (optional)
  # @param filter_updated_since character  (optional)
  # @param filter_host character If set, limit results to genomes extracted from this host (Taxonomy ID or name) All hosts by default (optional)
  # @param filter_pangolin_classification character If set, limit results to genomes classified to this lineage by the PangoLearn tool. (optional)
  # @param filter_geo_location character Assemblies from this location (country or continent) (optional)
  # @param filter_usa_state character Assemblies from this state (official two letter code only) (optional)
  # @param filter_complete_only character only include complete genomes. (optional)
  # @param table_fields array[character] Specify which fields to include in the tabular report (optional)
  # @param page_size integer The maximum number of virus data reports to return. Default is 20 and maximum is 1000. If the number of results exceeds the page size, `page_token` can be used to retrieve the remaining results. (optional)
  # @param page_token character A page token is returned from a `GetVirusDataReports` call with more than `page_size` results. Use this token, along with the previous `VirusDataReportRequest` parameters, to retrieve the next page of results. When `page_token` is empty, all results have been retrieved. (optional)
  # @return [V2reportsVirusAnnotationReportPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusAnnotationReportsByPost", {
  # tests for VirusAnnotationReportsByPost
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get virus annotation report by POST
  # Get virus annotation report. By default, in paged JSON format, but also available as tabular (accept: text/tab-separated-values) or json-lines (accept: application/x-ndjson)
  # @param v2_virus_annotation_report_request V2VirusAnnotationReportRequest 
  # @return [V2reportsVirusAnnotationReportPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusAnnotationReportsByTaxon", {
  # tests for VirusAnnotationReportsByTaxon
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get virus annotation report by taxon
  # Get virus annotation report by taxon. By default, in paged JSON format, but also available as tabular (accept: text/tab-separated-values) or json-lines (accept: application/x-ndjson)
  # @param taxon character NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank
  # @param filter_refseq_only character If true, limit results to RefSeq genomes. (optional)
  # @param filter_annotated_only character If true, limit results to annotated genomes. (optional)
  # @param filter_released_since character If set, limit results to viral genomes that have been released after a specified date (and optionally, time). April 1, 2020 midnight UTC should be formatted as '2020-04-01T00:00:00.000Z' (optional)
  # @param filter_updated_since character  (optional)
  # @param filter_host character If set, limit results to genomes extracted from this host (Taxonomy ID or name) All hosts by default (optional)
  # @param filter_pangolin_classification character If set, limit results to genomes classified to this lineage by the PangoLearn tool. (optional)
  # @param filter_geo_location character Assemblies from this location (country or continent) (optional)
  # @param filter_usa_state character Assemblies from this state (official two letter code only) (optional)
  # @param filter_complete_only character only include complete genomes. (optional)
  # @param table_fields array[character] Specify which fields to include in the tabular report (optional)
  # @param page_size integer The maximum number of virus data reports to return. Default is 20 and maximum is 1000. If the number of results exceeds the page size, `page_token` can be used to retrieve the remaining results. (optional)
  # @param page_token character A page token is returned from a `GetVirusDataReports` call with more than `page_size` results. Use this token, along with the previous `VirusDataReportRequest` parameters, to retrieve the next page of results. When `page_token` is empty, all results have been retrieved. (optional)
  # @return [V2reportsVirusAnnotationReportPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusGenomeDownload", {
  # tests for VirusGenomeDownload
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Download a virus genome dataset by taxon
  # Download a virus genome dataset by taxon
  # @param taxon character NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank
  # @param taxons array[character] NCBI Taxonomy IDs or names (common or scientific) at any taxonomic rank (optional)
  # @param refseq_only character If true, limit results to RefSeq genomes. (optional)
  # @param annotated_only character If true, limit results to annotated genomes. (optional)
  # @param released_since character If set, limit results to viral genomes that have been released after a specified date (and optionally, time). April 1, 2020 midnight UTC should be formatted as '2020-04-01T00:00:00.000Z' (optional)
  # @param updated_since character  (optional)
  # @param host character If set, limit results to genomes extracted from this host (Taxonomy ID or name) All hosts by default (optional)
  # @param pangolin_classification character If set, limit results to genomes classified to this lineage by the PangoLearn tool. (optional)
  # @param geo_location character Assemblies from this location (country or continent) (optional)
  # @param usa_state character Assemblies from this state (official two letter code only) (optional)
  # @param complete_only character only include complete genomes. (optional)
  # @param include_sequence array[V2ViralSequenceType] specify which sequence files to include in the download (optional)
  # @param aux_report array[V2VirusDatasetReportType] list additional reports to include with download. Data report is included by default. (optional)
  # @param use_psg character Experimental approach to retrieving sequence data. (optional)
  # @param filename character Output file name. (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusGenomeDownloadAccession", {
  # tests for VirusGenomeDownloadAccession
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Download a virus genome dataset by accession
  # Download a virus genome dataset by accession
  # @param accessions array[character] genome sequence accessions
  # @param taxons array[character] NCBI Taxonomy IDs or names (common or scientific) at any taxonomic rank (optional)
  # @param refseq_only character If true, limit results to RefSeq genomes. (optional)
  # @param annotated_only character If true, limit results to annotated genomes. (optional)
  # @param released_since character If set, limit results to viral genomes that have been released after a specified date (and optionally, time). April 1, 2020 midnight UTC should be formatted as '2020-04-01T00:00:00.000Z' (optional)
  # @param updated_since character  (optional)
  # @param host character If set, limit results to genomes extracted from this host (Taxonomy ID or name) All hosts by default (optional)
  # @param pangolin_classification character If set, limit results to genomes classified to this lineage by the PangoLearn tool. (optional)
  # @param geo_location character Assemblies from this location (country or continent) (optional)
  # @param usa_state character Assemblies from this state (official two letter code only) (optional)
  # @param complete_only character only include complete genomes. (optional)
  # @param include_sequence array[V2ViralSequenceType] specify which sequence files to include in the download (optional)
  # @param aux_report array[V2VirusDatasetReportType] list additional reports to include with download. Data report is included by default. (optional)
  # @param use_psg character Experimental approach to retrieving sequence data. (optional)
  # @param filename character Output file name. (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusGenomeDownloadPost", {
  # tests for VirusGenomeDownloadPost
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get a virus genome dataset by post
  # The &#39;GET&#39; version of download is limited by the size of the GET URL (2KB, which works out to about 140 genomic accessions).  The POST operation is provided to allow users to supply a larger number of accessions in a single request.
  # @param v2_virus_dataset_request V2VirusDatasetRequest 
  # @param filename character Output file name. (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusGenomeSummary", {
  # tests for VirusGenomeSummary
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get summary data for virus genomes by taxon
  # Get summary data and download by command line instructions for virus genomes by taxon.
  # @param taxon character NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank
  # @param accessions array[character] genome sequence accessions (optional)
  # @param refseq_only character If true, limit results to RefSeq genomes. (optional)
  # @param annotated_only character If true, limit results to annotated genomes. (optional)
  # @param released_since character If set, limit results to viral genomes that have been released after a specified date (and optionally, time). April 1, 2020 midnight UTC should be formatted as '2020-04-01T00:00:00.000Z' (optional)
  # @param updated_since character  (optional)
  # @param host character If set, limit results to genomes extracted from this host (Taxonomy ID or name) All hosts by default (optional)
  # @param pangolin_classification character If set, limit results to genomes classified to this lineage by the PangoLearn tool. (optional)
  # @param geo_location character Assemblies from this location (country or continent) (optional)
  # @param usa_state character Assemblies from this state (official two letter code only) (optional)
  # @param complete_only character only include complete genomes. (optional)
  # @param include_sequence array[V2ViralSequenceType] specify which sequence files to include in the download (optional)
  # @param aux_report array[V2VirusDatasetReportType] list additional reports to include with download. Data report is included by default. (optional)
  # @return [V2DownloadSummary]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusGenomeSummaryByPost", {
  # tests for VirusGenomeSummaryByPost
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get summary data for virus genomes by post
  # Get summary data and download by command line instructions for virus genomes by taxon.
  # @param v2_virus_dataset_request V2VirusDatasetRequest 
  # @return [V2DownloadSummary]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusGenomeTable", {
  # tests for VirusGenomeTable
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get virus genome metadata in a tabular format.
  # Get virus genome metadata in tabular format for virus genomes by taxon.
  # @param taxon character NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank
  # @param accessions array[character] genome sequence accessions (optional)
  # @param refseq_only character If true, limit results to RefSeq genomes. (optional)
  # @param annotated_only character If true, limit results to annotated genomes. (optional)
  # @param released_since character If set, limit results to viral genomes that have been released after a specified date (and optionally, time). April 1, 2020 midnight UTC should be formatted as '2020-04-01T00:00:00.000Z' (optional)
  # @param updated_since character  (optional)
  # @param host character If set, limit results to genomes extracted from this host (Taxonomy ID or name) All hosts by default (optional)
  # @param pangolin_classification character If set, limit results to genomes classified to this lineage by the PangoLearn tool. (optional)
  # @param geo_location character Assemblies from this location (country or continent) (optional)
  # @param usa_state character Assemblies from this state (official two letter code only) (optional)
  # @param complete_only character only include complete genomes. (optional)
  # @param table_fields array[V2VirusTableField] Specify which fields to include in the tabular report (optional)
  # @param include_sequence array[V2ViralSequenceType] specify which sequence files to include in the download (optional)
  # @param aux_report array[V2VirusDatasetReportType] list additional reports to include with download. Data report is included by default. (optional)
  # @param format V2TableFormat Choose download format (tsv, csv or jsonl) (optional)
  # @return [V2TabularOutput]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusReportsByAcessions", {
  # tests for VirusReportsByAcessions
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get virus metadata by accession
  # Get virus metadata by accesion. By default, in paged JSON format, but also available as tabular (accept: text/tab-separated-values) or json-lines (accept: application/x-ndjson)
  # @param accessions array[character] genome sequence accessions
  # @param filter_refseq_only character If true, limit results to RefSeq genomes. (optional)
  # @param filter_annotated_only character If true, limit results to annotated genomes. (optional)
  # @param filter_released_since character If set, limit results to viral genomes that have been released after a specified date (and optionally, time). April 1, 2020 midnight UTC should be formatted as '2020-04-01T00:00:00.000Z' (optional)
  # @param filter_updated_since character  (optional)
  # @param filter_host character If set, limit results to genomes extracted from this host (Taxonomy ID or name) All hosts by default (optional)
  # @param filter_pangolin_classification character If set, limit results to genomes classified to this lineage by the PangoLearn tool. (optional)
  # @param filter_geo_location character Assemblies from this location (country or continent) (optional)
  # @param filter_usa_state character Assemblies from this state (official two letter code only) (optional)
  # @param filter_complete_only character only include complete genomes. (optional)
  # @param returned_content V2VirusDataReportRequestContentType Return either virus genome accessions, or complete virus metadata (optional)
  # @param table_fields array[character] Specify which fields to include in the tabular report (optional)
  # @param page_size integer The maximum number of virus data reports to return. Default is 20 and maximum is 1000. If the number of results exceeds the page size, `page_token` can be used to retrieve the remaining results. (optional)
  # @param page_token character A page token is returned from a `GetVirusDataReports` call with more than `page_size` results. Use this token, along with the previous `VirusDataReportRequest` parameters, to retrieve the next page of results. When `page_token` is empty, all results have been retrieved. (optional)
  # @return [V2reportsVirusDataReportPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusReportsByPost", {
  # tests for VirusReportsByPost
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get virus metadata by POST
  # Get virus metadata. By default, in paged JSON format, but also available as tabular (accept: text/tab-separated-values) or json-lines (accept: application/x-ndjson)
  # @param v2_virus_data_report_request V2VirusDataReportRequest 
  # @return [V2reportsVirusDataReportPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("VirusReportsByTaxon", {
  # tests for VirusReportsByTaxon
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get virus metadata by taxon
  # Get virus metadata by taxon. By default, in paged JSON format, but also available as tabular (accept: text/tab-separated-values) or json-lines (accept: application/x-ndjson)
  # @param taxon character NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank
  # @param filter_refseq_only character If true, limit results to RefSeq genomes. (optional)
  # @param filter_annotated_only character If true, limit results to annotated genomes. (optional)
  # @param filter_released_since character If set, limit results to viral genomes that have been released after a specified date (and optionally, time). April 1, 2020 midnight UTC should be formatted as '2020-04-01T00:00:00.000Z' (optional)
  # @param filter_updated_since character  (optional)
  # @param filter_host character If set, limit results to genomes extracted from this host (Taxonomy ID or name) All hosts by default (optional)
  # @param filter_pangolin_classification character If set, limit results to genomes classified to this lineage by the PangoLearn tool. (optional)
  # @param filter_geo_location character Assemblies from this location (country or continent) (optional)
  # @param filter_usa_state character Assemblies from this state (official two letter code only) (optional)
  # @param filter_complete_only character only include complete genomes. (optional)
  # @param returned_content V2VirusDataReportRequestContentType Return either virus genome accessions, or complete virus metadata (optional)
  # @param table_fields array[character] Specify which fields to include in the tabular report (optional)
  # @param page_size integer The maximum number of virus data reports to return. Default is 20 and maximum is 1000. If the number of results exceeds the page size, `page_token` can be used to retrieve the remaining results. (optional)
  # @param page_token character A page token is returned from a `GetVirusDataReports` call with more than `page_size` results. Use this token, along with the previous `VirusDataReportRequest` parameters, to retrieve the next page of results. When `page_token` is empty, all results have been retrieved. (optional)
  # @return [V2reportsVirusDataReportPage]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
