# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2archiveModifier")

model_instance <- V2archiveModifier$new()

test_that("subtype", {
  # tests for the property `subtype` (V2archiveTaxonomySubtype)

  # uncomment below to test the property
  #expect_equal(model.instance$`subtype`, "EXPECTED_RESULT")
})

test_that("subname", {
  # tests for the property `subname` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`subname`, "EXPECTED_RESULT")
})
