# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyTaxIdsPage")

model_instance <- V2TaxonomyTaxIdsPage$new()

test_that("tax_ids", {
  # tests for the property `tax_ids` (array[integer])

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_ids`, "EXPECTED_RESULT")
})

test_that("next_page_token", {
  # tests for the property `next_page_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`next_page_token`, "EXPECTED_RESULT")
})
