# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2VirusAvailability")

model_instance <- V2VirusAvailability$new()

test_that("valid_accessions", {
  # tests for the property `valid_accessions` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`valid_accessions`, "EXPECTED_RESULT")
})

test_that("invalid_accessions", {
  # tests for the property `invalid_accessions` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`invalid_accessions`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})
