# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsProcessMetadata")

model_instance <- V2reportsProcessMetadata$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("go_id", {
  # tests for the property `go_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`go_id`, "EXPECTED_RESULT")
})

test_that("evidence_code", {
  # tests for the property `evidence_code` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`evidence_code`, "EXPECTED_RESULT")
})

test_that("qualifier", {
  # tests for the property `qualifier` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`qualifier`, "EXPECTED_RESULT")
})

test_that("reference", {
  # tests for the property `reference` (V2reportsReference)

  # uncomment below to test the property
  #expect_equal(model.instance$`reference`, "EXPECTED_RESULT")
})
