# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsBioSampleAttribute")

model_instance <- V2reportsBioSampleAttribute$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("value", {
  # tests for the property `value` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`value`, "EXPECTED_RESULT")
})
