# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsAnnotationInfo")

model_instance <- V2reportsAnnotationInfo$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("provider", {
  # tests for the property `provider` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`provider`, "EXPECTED_RESULT")
})

test_that("release_date", {
  # tests for the property `release_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`release_date`, "EXPECTED_RESULT")
})

test_that("report_url", {
  # tests for the property `report_url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`report_url`, "EXPECTED_RESULT")
})

test_that("stats", {
  # tests for the property `stats` (V2reportsFeatureCounts)

  # uncomment below to test the property
  #expect_equal(model.instance$`stats`, "EXPECTED_RESULT")
})

test_that("busco", {
  # tests for the property `busco` (V2reportsBuscoStat)

  # uncomment below to test the property
  #expect_equal(model.instance$`busco`, "EXPECTED_RESULT")
})

test_that("method", {
  # tests for the property `method` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`method`, "EXPECTED_RESULT")
})

test_that("pipeline", {
  # tests for the property `pipeline` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`pipeline`, "EXPECTED_RESULT")
})

test_that("software_version", {
  # tests for the property `software_version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`software_version`, "EXPECTED_RESULT")
})

test_that("status", {
  # tests for the property `status` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`status`, "EXPECTED_RESULT")
})

test_that("release_version", {
  # tests for the property `release_version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`release_version`, "EXPECTED_RESULT")
})
