# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsInfraspecificNames")

model_instance <- V2reportsInfraspecificNames$new()

test_that("breed", {
  # tests for the property `breed` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`breed`, "EXPECTED_RESULT")
})

test_that("cultivar", {
  # tests for the property `cultivar` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`cultivar`, "EXPECTED_RESULT")
})

test_that("ecotype", {
  # tests for the property `ecotype` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ecotype`, "EXPECTED_RESULT")
})

test_that("isolate", {
  # tests for the property `isolate` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isolate`, "EXPECTED_RESULT")
})

test_that("sex", {
  # tests for the property `sex` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sex`, "EXPECTED_RESULT")
})

test_that("strain", {
  # tests for the property `strain` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`strain`, "EXPECTED_RESULT")
})
