# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2GeneCountsByTaxonReply")

model_instance <- V2GeneCountsByTaxonReply$new()

test_that("report", {
  # tests for the property `report` (array[V2GeneCountsByTaxonReplyGeneTypeAndCount])

  # uncomment below to test the property
  #expect_equal(model.instance$`report`, "EXPECTED_RESULT")
})
