# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsAssemblyRevision")

model_instance <- V2reportsAssemblyRevision$new()

test_that("genbank_accession", {
  # tests for the property `genbank_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`genbank_accession`, "EXPECTED_RESULT")
})

test_that("refseq_accession", {
  # tests for the property `refseq_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`refseq_accession`, "EXPECTED_RESULT")
})

test_that("assembly_name", {
  # tests for the property `assembly_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_name`, "EXPECTED_RESULT")
})

test_that("assembly_level", {
  # tests for the property `assembly_level` (V2reportsAssemblyLevel)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_level`, "EXPECTED_RESULT")
})

test_that("release_date", {
  # tests for the property `release_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`release_date`, "EXPECTED_RESULT")
})

test_that("submission_date", {
  # tests for the property `submission_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`submission_date`, "EXPECTED_RESULT")
})

test_that("sequencing_technology", {
  # tests for the property `sequencing_technology` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequencing_technology`, "EXPECTED_RESULT")
})

test_that("identical", {
  # tests for the property `identical` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`identical`, "EXPECTED_RESULT")
})
