# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsAssemblyInfo")

model_instance <- V2reportsAssemblyInfo$new()

test_that("assembly_level", {
  # tests for the property `assembly_level` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_level`, "EXPECTED_RESULT")
})

test_that("assembly_status", {
  # tests for the property `assembly_status` (V2reportsAssemblyStatus)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_status`, "EXPECTED_RESULT")
})

test_that("paired_assembly", {
  # tests for the property `paired_assembly` (V2reportsPairedAssembly)

  # uncomment below to test the property
  #expect_equal(model.instance$`paired_assembly`, "EXPECTED_RESULT")
})

test_that("assembly_name", {
  # tests for the property `assembly_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_name`, "EXPECTED_RESULT")
})

test_that("assembly_long_name", {
  # tests for the property `assembly_long_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_long_name`, "EXPECTED_RESULT")
})

test_that("assembly_type", {
  # tests for the property `assembly_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_type`, "EXPECTED_RESULT")
})

test_that("bioproject_lineage", {
  # tests for the property `bioproject_lineage` (array[V2reportsBioProjectLineage])

  # uncomment below to test the property
  #expect_equal(model.instance$`bioproject_lineage`, "EXPECTED_RESULT")
})

test_that("bioproject_accession", {
  # tests for the property `bioproject_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`bioproject_accession`, "EXPECTED_RESULT")
})

test_that("submission_date", {
  # tests for the property `submission_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`submission_date`, "EXPECTED_RESULT")
})

test_that("release_date", {
  # tests for the property `release_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`release_date`, "EXPECTED_RESULT")
})

test_that("description", {
  # tests for the property `description` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`description`, "EXPECTED_RESULT")
})

test_that("submitter", {
  # tests for the property `submitter` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`submitter`, "EXPECTED_RESULT")
})

test_that("refseq_category", {
  # tests for the property `refseq_category` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`refseq_category`, "EXPECTED_RESULT")
})

test_that("synonym", {
  # tests for the property `synonym` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`synonym`, "EXPECTED_RESULT")
})

test_that("linked_assembly", {
  # tests for the property `linked_assembly` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`linked_assembly`, "EXPECTED_RESULT")
})

test_that("linked_assemblies", {
  # tests for the property `linked_assemblies` (array[V2reportsLinkedAssembly])

  # uncomment below to test the property
  #expect_equal(model.instance$`linked_assemblies`, "EXPECTED_RESULT")
})

test_that("atypical", {
  # tests for the property `atypical` (V2reportsAtypicalInfo)

  # uncomment below to test the property
  #expect_equal(model.instance$`atypical`, "EXPECTED_RESULT")
})

test_that("genome_notes", {
  # tests for the property `genome_notes` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`genome_notes`, "EXPECTED_RESULT")
})

test_that("sequencing_tech", {
  # tests for the property `sequencing_tech` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sequencing_tech`, "EXPECTED_RESULT")
})

test_that("assembly_method", {
  # tests for the property `assembly_method` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_method`, "EXPECTED_RESULT")
})

test_that("grouping_method", {
  # tests for the property `grouping_method` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`grouping_method`, "EXPECTED_RESULT")
})

test_that("biosample", {
  # tests for the property `biosample` (V2reportsBioSampleDescriptor)

  # uncomment below to test the property
  #expect_equal(model.instance$`biosample`, "EXPECTED_RESULT")
})

test_that("blast_url", {
  # tests for the property `blast_url` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`blast_url`, "EXPECTED_RESULT")
})

test_that("comments", {
  # tests for the property `comments` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`comments`, "EXPECTED_RESULT")
})

test_that("suppression_reason", {
  # tests for the property `suppression_reason` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`suppression_reason`, "EXPECTED_RESULT")
})

test_that("diploid_role", {
  # tests for the property `diploid_role` (V2reportsLinkedAssemblyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`diploid_role`, "EXPECTED_RESULT")
})
