# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2GeneLinksReply")

model_instance <- V2GeneLinksReply$new()

test_that("gene_links", {
  # tests for the property `gene_links` (array[V2GeneLinksReplyGeneLink])

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_links`, "EXPECTED_RESULT")
})
