# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsLinkedAssembly")

model_instance <- V2reportsLinkedAssembly$new()

test_that("linked_assembly", {
  # tests for the property `linked_assembly` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`linked_assembly`, "EXPECTED_RESULT")
})

test_that("assembly_type", {
  # tests for the property `assembly_type` (V2reportsLinkedAssemblyType)

  # uncomment below to test the property
  #expect_equal(model.instance$`assembly_type`, "EXPECTED_RESULT")
})
