# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2GenePubmedIdsRequest")

model_instance <- V2GenePubmedIdsRequest$new()

test_that("gene_ids", {
  # tests for the property `gene_ids` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`gene_ids`, "EXPECTED_RESULT")
})
