# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsNameAndAuthorityNote")

model_instance <- V2reportsNameAndAuthorityNote$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("note", {
  # tests for the property `note` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`note`, "EXPECTED_RESULT")
})

test_that("note_classifier", {
  # tests for the property `note_classifier` (V2reportsNameAndAuthorityNoteClassifier)

  # uncomment below to test the property
  #expect_equal(model.instance$`note_classifier`, "EXPECTED_RESULT")
})
