# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test OrganelleApi")

api_instance <- OrganelleApi$new()

test_that("DownloadOrganellePackage", {
  # tests for DownloadOrganellePackage
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get a organelle data package by accesions
  # Download a organelle data report and annotation data package.
  # @param accessions array[character] NCBI organelle assembly accessions
  # @param exclude_sequence character Set to true to omit the genomic sequence. (optional)
  # @param include_annotation_type array[V2AnnotationForOrganelleType] Select additional types of annotation to include in the data package.  If unset, no annotation is provided. (optional)
  # @param filename character Output file name. (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("DownloadOrganellePackageByPost", {
  # tests for DownloadOrganellePackageByPost
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get a organelle data package by post
  # Download a organelle report and annotation data package by post.
  # @param v2_organelle_download_request V2OrganelleDownloadRequest 
  # @param filename character Output file name. (optional)
  # @return [data.frame]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("OrganelleDatareportByAccession", {
  # tests for OrganelleDatareportByAccession
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get Organelle dataset report by accession
  # Get Organelle dataset report by accession.
  # @param accessions array[character] NCBI assembly accession
  # @param taxons array[character] NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank (optional)
  # @param organelle_types array[V2reportsOrganelleType]  (optional)
  # @param first_release_date character Only return organelle assemblies that were released on or after the specified date By default, do not filter. (optional)
  # @param last_release_date character Only return organelle assemblies that were released on or before to the specified date By default, do not filter. (optional)
  # @param tax_exact_match character If true, only return assemblies with the given NCBI Taxonomy ID, or name. Otherwise, assemblies from taxonomy subtree are included, too. (optional)
  # @param sort_field character  (optional)
  # @param sort_direction V2SortDirection  (optional)
  # @param returned_content V2OrganelleMetadataRequestContentType Return either assembly accessions, or entire assembly-metadata records (optional)
  # @param table_format V2OrganelleMetadataRequestOrganelleTableFormat Optional pre-defined template for processing a tabular data request (optional)
  # @param include_tabular_header V2IncludeTabularHeader Whether this request for tabular data should include the header row (optional)
  # @return [V2reportsOrganelleDataReports]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("OrganelleDatareportByPost", {
  # tests for OrganelleDatareportByPost
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get Organelle dataset report by http post
  # Get Organelle dataset report by http post.
  # @param v2_organelle_metadata_request V2OrganelleMetadataRequest 
  # @return [V2reportsOrganelleDataReports]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("OrganelleDatareportByTaxon", {
  # tests for OrganelleDatareportByTaxon
  # base path: https://api.ncbi.nlm.nih.gov/datasets/v2
  # Get Organelle dataset report by taxons
  # Get Organelle dataset report by taxons.
  # @param taxons array[character] NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank
  # @param organelle_types array[V2reportsOrganelleType]  (optional)
  # @param first_release_date character Only return organelle assemblies that were released on or after the specified date By default, do not filter. (optional)
  # @param last_release_date character Only return organelle assemblies that were released on or before to the specified date By default, do not filter. (optional)
  # @param tax_exact_match character If true, only return assemblies with the given NCBI Taxonomy ID, or name. Otherwise, assemblies from taxonomy subtree are included, too. (optional)
  # @param sort_field character  (optional)
  # @param sort_direction V2SortDirection  (optional)
  # @param returned_content V2OrganelleMetadataRequestContentType Return either assembly accessions, or entire assembly-metadata records (optional)
  # @param page_size integer The maximum number of organelle assemblies to return. Default is 20 and maximum is 1000. If the number of results exceeds the page size, `page_token` can be used to retrieve the remaining results. (optional)
  # @param page_token character A page token is returned from an `OrganelleMetadata` call with more than `page_size` results. Use this token, along with the previous `OrganelleMetadata` parameters, to retrieve the next page of results. When `page_token` is empty, all results have been retrieved. (optional)
  # @param table_format V2OrganelleMetadataRequestOrganelleTableFormat Optional pre-defined template for processing a tabular data request (optional)
  # @param include_tabular_header V2IncludeTabularHeader Whether this request for tabular data should include the header row (optional)
  # @return [V2reportsOrganelleDataReports]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
