# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsAdditionalSubmitter")

model_instance <- V2reportsAdditionalSubmitter$new()

test_that("genbank_accession", {
  # tests for the property `genbank_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`genbank_accession`, "EXPECTED_RESULT")
})

test_that("refseq_accession", {
  # tests for the property `refseq_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`refseq_accession`, "EXPECTED_RESULT")
})

test_that("chr_name", {
  # tests for the property `chr_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`chr_name`, "EXPECTED_RESULT")
})

test_that("molecule_type", {
  # tests for the property `molecule_type` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`molecule_type`, "EXPECTED_RESULT")
})

test_that("submitter", {
  # tests for the property `submitter` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`submitter`, "EXPECTED_RESULT")
})

test_that("bioproject_accession", {
  # tests for the property `bioproject_accession` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`bioproject_accession`, "EXPECTED_RESULT")
})
