# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsRange")

model_instance <- V2reportsRange$new()

test_that("begin", {
  # tests for the property `begin` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`begin`, "EXPECTED_RESULT")
})

test_that("end", {
  # tests for the property `end` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`end`, "EXPECTED_RESULT")
})

test_that("orientation", {
  # tests for the property `orientation` (V2reportsOrientation)

  # uncomment below to test the property
  #expect_equal(model.instance$`orientation`, "EXPECTED_RESULT")
})

test_that("order", {
  # tests for the property `order` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`order`, "EXPECTED_RESULT")
})

test_that("ribosomal_slippage", {
  # tests for the property `ribosomal_slippage` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`ribosomal_slippage`, "EXPECTED_RESULT")
})
