# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsGeneCounts")

model_instance <- V2reportsGeneCounts$new()

test_that("total", {
  # tests for the property `total` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`total`, "EXPECTED_RESULT")
})

test_that("protein_coding", {
  # tests for the property `protein_coding` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`protein_coding`, "EXPECTED_RESULT")
})

test_that("non_coding", {
  # tests for the property `non_coding` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`non_coding`, "EXPECTED_RESULT")
})

test_that("pseudogene", {
  # tests for the property `pseudogene` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`pseudogene`, "EXPECTED_RESULT")
})

test_that("other", {
  # tests for the property `other` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`other`, "EXPECTED_RESULT")
})
