# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsBioProjectLineage")

model_instance <- V2reportsBioProjectLineage$new()

test_that("bioprojects", {
  # tests for the property `bioprojects` (array[V2reportsBioProject])

  # uncomment below to test the property
  #expect_equal(model.instance$`bioprojects`, "EXPECTED_RESULT")
})
