# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsNameAndAuthorityPublication")

model_instance <- V2reportsNameAndAuthorityPublication$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("citation", {
  # tests for the property `citation` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`citation`, "EXPECTED_RESULT")
})
