# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsProtein")

model_instance <- V2reportsProtein$new()

test_that("accession_version", {
  # tests for the property `accession_version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`accession_version`, "EXPECTED_RESULT")
})

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("length", {
  # tests for the property `length` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`length`, "EXPECTED_RESULT")
})

test_that("isoform_name", {
  # tests for the property `isoform_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`isoform_name`, "EXPECTED_RESULT")
})

test_that("ensembl_protein", {
  # tests for the property `ensembl_protein` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`ensembl_protein`, "EXPECTED_RESULT")
})

test_that("mature_peptides", {
  # tests for the property `mature_peptides` (array[V2reportsMaturePeptide])

  # uncomment below to test the property
  #expect_equal(model.instance$`mature_peptides`, "EXPECTED_RESULT")
})
