# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsNameAndAuthority")

model_instance <- V2reportsNameAndAuthority$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("authority", {
  # tests for the property `authority` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`authority`, "EXPECTED_RESULT")
})

test_that("type_strains", {
  # tests for the property `type_strains` (array[V2reportsTaxonomyTypeMaterial])

  # uncomment below to test the property
  #expect_equal(model.instance$`type_strains`, "EXPECTED_RESULT")
})

test_that("curator_synonym", {
  # tests for the property `curator_synonym` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`curator_synonym`, "EXPECTED_RESULT")
})

test_that("homotypic_synonyms", {
  # tests for the property `homotypic_synonyms` (array[V2reportsNameAndAuthority])

  # uncomment below to test the property
  #expect_equal(model.instance$`homotypic_synonyms`, "EXPECTED_RESULT")
})

test_that("heterotypic_synonyms", {
  # tests for the property `heterotypic_synonyms` (array[V2reportsNameAndAuthority])

  # uncomment below to test the property
  #expect_equal(model.instance$`heterotypic_synonyms`, "EXPECTED_RESULT")
})

test_that("other_synonyms", {
  # tests for the property `other_synonyms` (array[V2reportsNameAndAuthority])

  # uncomment below to test the property
  #expect_equal(model.instance$`other_synonyms`, "EXPECTED_RESULT")
})

test_that("informal_names", {
  # tests for the property `informal_names` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`informal_names`, "EXPECTED_RESULT")
})

test_that("basionym", {
  # tests for the property `basionym` (V2reportsNameAndAuthority)

  # uncomment below to test the property
  #expect_equal(model.instance$`basionym`, "EXPECTED_RESULT")
})

test_that("publications", {
  # tests for the property `publications` (array[V2reportsNameAndAuthorityPublication])

  # uncomment below to test the property
  #expect_equal(model.instance$`publications`, "EXPECTED_RESULT")
})

test_that("notes", {
  # tests for the property `notes` (array[V2reportsNameAndAuthorityNote])

  # uncomment below to test the property
  #expect_equal(model.instance$`notes`, "EXPECTED_RESULT")
})

test_that("formal", {
  # tests for the property `formal` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`formal`, "EXPECTED_RESULT")
})
