# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2OrganelleMetadataRequest")

model_instance <- V2OrganelleMetadataRequest$new()

test_that("taxons", {
  # tests for the property `taxons` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`taxons`, "EXPECTED_RESULT")
})

test_that("accessions", {
  # tests for the property `accessions` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`accessions`, "EXPECTED_RESULT")
})

test_that("organelle_types", {
  # tests for the property `organelle_types` (array[V2reportsOrganelleType])

  # uncomment below to test the property
  #expect_equal(model.instance$`organelle_types`, "EXPECTED_RESULT")
})

test_that("first_release_date", {
  # tests for the property `first_release_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`first_release_date`, "EXPECTED_RESULT")
})

test_that("last_release_date", {
  # tests for the property `last_release_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`last_release_date`, "EXPECTED_RESULT")
})

test_that("tax_exact_match", {
  # tests for the property `tax_exact_match` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`tax_exact_match`, "EXPECTED_RESULT")
})

test_that("sort", {
  # tests for the property `sort` (array[V2OrganelleSort])

  # uncomment below to test the property
  #expect_equal(model.instance$`sort`, "EXPECTED_RESULT")
})

test_that("returned_content", {
  # tests for the property `returned_content` (V2OrganelleMetadataRequestContentType)

  # uncomment below to test the property
  #expect_equal(model.instance$`returned_content`, "EXPECTED_RESULT")
})

test_that("page_size", {
  # tests for the property `page_size` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`page_size`, "EXPECTED_RESULT")
})

test_that("page_token", {
  # tests for the property `page_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`page_token`, "EXPECTED_RESULT")
})

test_that("table_format", {
  # tests for the property `table_format` (V2OrganelleMetadataRequestOrganelleTableFormat)

  # uncomment below to test the property
  #expect_equal(model.instance$`table_format`, "EXPECTED_RESULT")
})

test_that("include_tabular_header", {
  # tests for the property `include_tabular_header` (V2IncludeTabularHeader)

  # uncomment below to test the property
  #expect_equal(model.instance$`include_tabular_header`, "EXPECTED_RESULT")
})
