# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsIsolate")

model_instance <- V2reportsIsolate$new()

test_that("name", {
  # tests for the property `name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`name`, "EXPECTED_RESULT")
})

test_that("source", {
  # tests for the property `source` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`source`, "EXPECTED_RESULT")
})

test_that("collection_date", {
  # tests for the property `collection_date` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`collection_date`, "EXPECTED_RESULT")
})
