# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyMetadataResponse")

model_instance <- V2TaxonomyMetadataResponse$new()

test_that("messages", {
  # tests for the property `messages` (array[V2reportsMessage])

  # uncomment below to test the property
  #expect_equal(model.instance$`messages`, "EXPECTED_RESULT")
})

test_that("taxonomy_nodes", {
  # tests for the property `taxonomy_nodes` (array[V2TaxonomyMatch])

  # uncomment below to test the property
  #expect_equal(model.instance$`taxonomy_nodes`, "EXPECTED_RESULT")
})
