# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2reportsBioSampleContact")

model_instance <- V2reportsBioSampleContact$new()

test_that("lab", {
  # tests for the property `lab` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`lab`, "EXPECTED_RESULT")
})
