# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test V2TaxonomyMetadataRequest")

model_instance <- V2TaxonomyMetadataRequest$new()

test_that("taxons", {
  # tests for the property `taxons` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`taxons`, "EXPECTED_RESULT")
})

test_that("returned_content", {
  # tests for the property `returned_content` (V2TaxonomyMetadataRequestContentType)

  # uncomment below to test the property
  #expect_equal(model.instance$`returned_content`, "EXPECTED_RESULT")
})

test_that("page_size", {
  # tests for the property `page_size` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`page_size`, "EXPECTED_RESULT")
})

test_that("include_tabular_header", {
  # tests for the property `include_tabular_header` (V2IncludeTabularHeader)

  # uncomment below to test the property
  #expect_equal(model.instance$`include_tabular_header`, "EXPECTED_RESULT")
})

test_that("page_token", {
  # tests for the property `page_token` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`page_token`, "EXPECTED_RESULT")
})

test_that("table_format", {
  # tests for the property `table_format` (V2TaxonomyMetadataRequestTableFormat)

  # uncomment below to test the property
  #expect_equal(model.instance$`table_format`, "EXPECTED_RESULT")
})

test_that("children", {
  # tests for the property `children` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`children`, "EXPECTED_RESULT")
})

test_that("ranks", {
  # tests for the property `ranks` (array[V2reportsRankType])

  # uncomment below to test the property
  #expect_equal(model.instance$`ranks`, "EXPECTED_RESULT")
})
