#' NCBI Datasets API
#'
#' ### NCBI Datasets is a resource that lets you easily gather data from NCBI. The Datasets version 2 API is still in alpha, and we're updating it often to add new functionality, iron out bugs and enhance usability. For some larger downloads, you may want to download a [dehydrated zip archive](https://www.ncbi.nlm.nih.gov/datasets/docs/v2/how-tos/genomes/large-download/), and retrieve the individual data files at a later time. 
#'
#' The version of the OpenAPI document: v2
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Organelle operations
#' @description OrganelleApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @examples
#' \dontrun{
#' ####################  DownloadOrganellePackage  ####################
#'
#' library(ncbiopenapi)
#' var_accessions <- c("inner_example") # array[character] | NCBI organelle assembly accessions
#' var_exclude_sequence <- "exclude_sequence_example" # character | Set to true to omit the genomic sequence. (Optional)
#' var_include_annotation_type <- c(v2AnnotationForOrganelleType$new()) # array[V2AnnotationForOrganelleType] | Select additional types of annotation to include in the data package.  If unset, no annotation is provided. (Optional)
#' var_filename <- "ncbi_dataset.zip" # character | Output file name. (Optional)
#'
#' #Get a organelle data package by accesions
#' api_instance <- OrganelleApi$new()
#'
#' # Configure API key authorization: ApiKeyAuthHeader
#' api_instance$api_client$api_keys["api-key"] <- Sys.getenv("API_KEY")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$DownloadOrganellePackage(var_accessions, exclude_sequence = var_exclude_sequence, include_annotation_type = var_include_annotation_type, filename = var_filenamedata_file = "result.txt")
#' result <- api_instance$DownloadOrganellePackage(var_accessions, exclude_sequence = var_exclude_sequence, include_annotation_type = var_include_annotation_type, filename = var_filename)
#' dput(result)
#'
#'
#' ####################  DownloadOrganellePackageByPost  ####################
#'
#' library(ncbiopenapi)
#' var_v2_organelle_download_request <- v2OrganelleDownloadRequest$new(c("accessions_example"), "exclude_sequence_example", c(v2AnnotationForOrganelleType$new())) # V2OrganelleDownloadRequest | 
#' var_filename <- "ncbi_dataset.zip" # character | Output file name. (Optional)
#'
#' #Get a organelle data package by post
#' api_instance <- OrganelleApi$new()
#'
#' # Configure API key authorization: ApiKeyAuthHeader
#' api_instance$api_client$api_keys["api-key"] <- Sys.getenv("API_KEY")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$DownloadOrganellePackageByPost(var_v2_organelle_download_request, filename = var_filenamedata_file = "result.txt")
#' result <- api_instance$DownloadOrganellePackageByPost(var_v2_organelle_download_request, filename = var_filename)
#' dput(result)
#'
#'
#' ####################  OrganelleDatareportByAccession  ####################
#'
#' library(ncbiopenapi)
#' var_accessions <- c("inner_example") # array[character] | NCBI assembly accession
#' var_taxons <- c("inner_example") # array[character] | NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank (Optional)
#' var_organelle_types <- c(v2reportsOrganelleType$new()) # array[V2reportsOrganelleType] |  (Optional)
#' var_first_release_date <- "2015-01-10T00:00:00Z" # character | Only return organelle assemblies that were released on or after the specified date By default, do not filter. (Optional)
#' var_last_release_date <- "2021-01-10T00:00:00Z" # character | Only return organelle assemblies that were released on or before to the specified date By default, do not filter. (Optional)
#' var_tax_exact_match <- FALSE # character | If true, only return assemblies with the given NCBI Taxonomy ID, or name. Otherwise, assemblies from taxonomy subtree are included, too. (Optional)
#' var_sort_field <- "sort_field_example" # character |  (Optional)
#' var_sort_direction <- v2SortDirection$new() # V2SortDirection |  (Optional)
#' var_returned_content <- v2OrganelleMetadataRequestContentType$new() # V2OrganelleMetadataRequestContentType | Return either assembly accessions, or entire assembly-metadata records (Optional)
#' var_table_format <- v2OrganelleMetadataRequestOrganelleTableFormat$new() # V2OrganelleMetadataRequestOrganelleTableFormat | Optional pre-defined template for processing a tabular data request (Optional)
#' var_include_tabular_header <- v2IncludeTabularHeader$new() # V2IncludeTabularHeader | Whether this request for tabular data should include the header row (Optional)
#'
#' #Get Organelle dataset report by accession
#' api_instance <- OrganelleApi$new()
#'
#' # Configure API key authorization: ApiKeyAuthHeader
#' api_instance$api_client$api_keys["api-key"] <- Sys.getenv("API_KEY")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$OrganelleDatareportByAccession(var_accessions, taxons = var_taxons, organelle_types = var_organelle_types, first_release_date = var_first_release_date, last_release_date = var_last_release_date, tax_exact_match = var_tax_exact_match, sort_field = var_sort_field, sort_direction = var_sort_direction, returned_content = var_returned_content, table_format = var_table_format, include_tabular_header = var_include_tabular_headerdata_file = "result.txt")
#' result <- api_instance$OrganelleDatareportByAccession(var_accessions, taxons = var_taxons, organelle_types = var_organelle_types, first_release_date = var_first_release_date, last_release_date = var_last_release_date, tax_exact_match = var_tax_exact_match, sort_field = var_sort_field, sort_direction = var_sort_direction, returned_content = var_returned_content, table_format = var_table_format, include_tabular_header = var_include_tabular_header)
#' dput(result)
#'
#'
#' ####################  OrganelleDatareportByPost  ####################
#'
#' library(ncbiopenapi)
#' var_v2_organelle_metadata_request <- v2OrganelleMetadataRequest$new(c("taxons_example"), c("accessions_example"), c(v2reportsOrganelleType$new()), "first_release_date_example", "last_release_date_example", "tax_exact_match_example", c(v2OrganelleSort$new("field_example", v2SortDirection$new())), v2OrganelleMetadataRequestContentType$new(), 123, "page_token_example", v2OrganelleMetadataRequestOrganelleTableFormat$new(), v2IncludeTabularHeader$new()) # V2OrganelleMetadataRequest | 
#'
#' #Get Organelle dataset report by http post
#' api_instance <- OrganelleApi$new()
#'
#' # Configure API key authorization: ApiKeyAuthHeader
#' api_instance$api_client$api_keys["api-key"] <- Sys.getenv("API_KEY")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$OrganelleDatareportByPost(var_v2_organelle_metadata_requestdata_file = "result.txt")
#' result <- api_instance$OrganelleDatareportByPost(var_v2_organelle_metadata_request)
#' dput(result)
#'
#'
#' ####################  OrganelleDatareportByTaxon  ####################
#'
#' library(ncbiopenapi)
#' var_taxons <- c("inner_example") # array[character] | NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank
#' var_organelle_types <- c(v2reportsOrganelleType$new()) # array[V2reportsOrganelleType] |  (Optional)
#' var_first_release_date <- "2015-01-10T00:00:00Z" # character | Only return organelle assemblies that were released on or after the specified date By default, do not filter. (Optional)
#' var_last_release_date <- "2021-01-10T00:00:00Z" # character | Only return organelle assemblies that were released on or before to the specified date By default, do not filter. (Optional)
#' var_tax_exact_match <- FALSE # character | If true, only return assemblies with the given NCBI Taxonomy ID, or name. Otherwise, assemblies from taxonomy subtree are included, too. (Optional)
#' var_sort_field <- "sort_field_example" # character |  (Optional)
#' var_sort_direction <- v2SortDirection$new() # V2SortDirection |  (Optional)
#' var_returned_content <- v2OrganelleMetadataRequestContentType$new() # V2OrganelleMetadataRequestContentType | Return either assembly accessions, or entire assembly-metadata records (Optional)
#' var_page_size <- 56 # integer | The maximum number of organelle assemblies to return. Default is 20 and maximum is 1000. If the number of results exceeds the page size, `page_token` can be used to retrieve the remaining results. (Optional)
#' var_page_token <- "page_token_example" # character | A page token is returned from an `OrganelleMetadata` call with more than `page_size` results. Use this token, along with the previous `OrganelleMetadata` parameters, to retrieve the next page of results. When `page_token` is empty, all results have been retrieved. (Optional)
#' var_table_format <- v2OrganelleMetadataRequestOrganelleTableFormat$new() # V2OrganelleMetadataRequestOrganelleTableFormat | Optional pre-defined template for processing a tabular data request (Optional)
#' var_include_tabular_header <- v2IncludeTabularHeader$new() # V2IncludeTabularHeader | Whether this request for tabular data should include the header row (Optional)
#'
#' #Get Organelle dataset report by taxons
#' api_instance <- OrganelleApi$new()
#'
#' # Configure API key authorization: ApiKeyAuthHeader
#' api_instance$api_client$api_keys["api-key"] <- Sys.getenv("API_KEY")
#'
#' # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#' # result <- api_instance$OrganelleDatareportByTaxon(var_taxons, organelle_types = var_organelle_types, first_release_date = var_first_release_date, last_release_date = var_last_release_date, tax_exact_match = var_tax_exact_match, sort_field = var_sort_field, sort_direction = var_sort_direction, returned_content = var_returned_content, page_size = var_page_size, page_token = var_page_token, table_format = var_table_format, include_tabular_header = var_include_tabular_headerdata_file = "result.txt")
#' result <- api_instance$OrganelleDatareportByTaxon(var_taxons, organelle_types = var_organelle_types, first_release_date = var_first_release_date, last_release_date = var_last_release_date, tax_exact_match = var_tax_exact_match, sort_field = var_sort_field, sort_direction = var_sort_direction, returned_content = var_returned_content, page_size = var_page_size, page_token = var_page_token, table_format = var_table_format, include_tabular_header = var_include_tabular_header)
#' dput(result)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
OrganelleApi <- R6::R6Class(
  "OrganelleApi",
  public = list(
    api_client = NULL,

    #' @description
    #' Initialize a new OrganelleApi.
    #'
    #' @param api_client An instance of API client.
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },

    #' @description
    #' Get a organelle data package by accesions
    #'
    #' @param accessions NCBI organelle assembly accessions
    #' @param exclude_sequence (optional) Set to true to omit the genomic sequence.
    #' @param include_annotation_type (optional) Select additional types of annotation to include in the data package.  If unset, no annotation is provided.
    #' @param filename (optional) Output file name. (default value: "ncbi_dataset.zip")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return data.frame
    DownloadOrganellePackage = function(accessions, exclude_sequence = NULL, include_annotation_type = NULL, filename = "ncbi_dataset.zip", data_file = NULL, ...) {
      local_var_response <- self$DownloadOrganellePackageWithHttpInfo(accessions, exclude_sequence, include_annotation_type, filename, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Get a organelle data package by accesions
    #'
    #' @param accessions NCBI organelle assembly accessions
    #' @param exclude_sequence (optional) Set to true to omit the genomic sequence.
    #' @param include_annotation_type (optional) Select additional types of annotation to include in the data package.  If unset, no annotation is provided.
    #' @param filename (optional) Output file name. (default value: "ncbi_dataset.zip")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (data.frame) with additional information such as HTTP status code, headers
    DownloadOrganellePackageWithHttpInfo = function(accessions, exclude_sequence = NULL, include_annotation_type = NULL, filename = "ncbi_dataset.zip", data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`accessions`)) {
        stop("Missing required parameter `accessions`.")
      }





      query_params[["exclude_sequence"]] <- `exclude_sequence`

      # explore
      for (query_item in `include_annotation_type`) {
        query_params[["include_annotation_type"]] <- c(query_params[["include_annotation_type"]], list(`include_annotation_type` = query_item))
      }

      query_params[["filename"]] <- `filename`

      local_var_url_path <- "/organelle/accession/{accessions}/download"
      if (!missing(`accessions`)) {
        local_var_url_path <- gsub("\\{accessions\\}", paste(URLencode(as.character(`accessions`), reserved = TRUE), collapse= ",", sep=""), local_var_url_path)
      }

      # API key authentication
      if ("api-key" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["api-key"]) > 0) {
        header_params["api-key"] <- paste(unlist(self$api_client$api_keys["api-key"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("text/plain", "application/zip")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "data.frame"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Get a organelle data package by post
    #'
    #' @param v2_organelle_download_request 
    #' @param filename (optional) Output file name. (default value: "ncbi_dataset.zip")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return data.frame
    DownloadOrganellePackageByPost = function(v2_organelle_download_request, filename = "ncbi_dataset.zip", data_file = NULL, ...) {
      local_var_response <- self$DownloadOrganellePackageByPostWithHttpInfo(v2_organelle_download_request, filename, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Get a organelle data package by post
    #'
    #' @param v2_organelle_download_request 
    #' @param filename (optional) Output file name. (default value: "ncbi_dataset.zip")
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (data.frame) with additional information such as HTTP status code, headers
    DownloadOrganellePackageByPostWithHttpInfo = function(v2_organelle_download_request, filename = "ncbi_dataset.zip", data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`v2_organelle_download_request`)) {
        stop("Missing required parameter `v2_organelle_download_request`.")
      }



      query_params[["filename"]] <- `filename`

      if (!is.null(`v2_organelle_download_request`)) {
        local_var_body <- `v2_organelle_download_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/organelle/download"
      # API key authentication
      if ("api-key" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["api-key"]) > 0) {
        header_params["api-key"] <- paste(unlist(self$api_client$api_keys["api-key"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("text/plain", "application/zip")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "data.frame"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Get Organelle dataset report by accession
    #'
    #' @param accessions NCBI assembly accession
    #' @param taxons (optional) NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank
    #' @param organelle_types (optional) No description
    #' @param first_release_date (optional) Only return organelle assemblies that were released on or after the specified date By default, do not filter.
    #' @param last_release_date (optional) Only return organelle assemblies that were released on or before to the specified date By default, do not filter.
    #' @param tax_exact_match (optional) If true, only return assemblies with the given NCBI Taxonomy ID, or name. Otherwise, assemblies from taxonomy subtree are included, too. (default value: FALSE)
    #' @param sort_field (optional) No description
    #' @param sort_direction (optional) No description
    #' @param returned_content (optional) Return either assembly accessions, or entire assembly-metadata records
    #' @param table_format (optional) Optional pre-defined template for processing a tabular data request
    #' @param include_tabular_header (optional) Whether this request for tabular data should include the header row
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return V2reportsOrganelleDataReports
    OrganelleDatareportByAccession = function(accessions, taxons = NULL, organelle_types = NULL, first_release_date = NULL, last_release_date = NULL, tax_exact_match = FALSE, sort_field = NULL, sort_direction = NULL, returned_content = NULL, table_format = NULL, include_tabular_header = NULL, data_file = NULL, ...) {
      local_var_response <- self$OrganelleDatareportByAccessionWithHttpInfo(accessions, taxons, organelle_types, first_release_date, last_release_date, tax_exact_match, sort_field, sort_direction, returned_content, table_format, include_tabular_header, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Get Organelle dataset report by accession
    #'
    #' @param accessions NCBI assembly accession
    #' @param taxons (optional) NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank
    #' @param organelle_types (optional) No description
    #' @param first_release_date (optional) Only return organelle assemblies that were released on or after the specified date By default, do not filter.
    #' @param last_release_date (optional) Only return organelle assemblies that were released on or before to the specified date By default, do not filter.
    #' @param tax_exact_match (optional) If true, only return assemblies with the given NCBI Taxonomy ID, or name. Otherwise, assemblies from taxonomy subtree are included, too. (default value: FALSE)
    #' @param sort_field (optional) No description
    #' @param sort_direction (optional) No description
    #' @param returned_content (optional) Return either assembly accessions, or entire assembly-metadata records
    #' @param table_format (optional) Optional pre-defined template for processing a tabular data request
    #' @param include_tabular_header (optional) Whether this request for tabular data should include the header row
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (V2reportsOrganelleDataReports) with additional information such as HTTP status code, headers
    OrganelleDatareportByAccessionWithHttpInfo = function(accessions, taxons = NULL, organelle_types = NULL, first_release_date = NULL, last_release_date = NULL, tax_exact_match = FALSE, sort_field = NULL, sort_direction = NULL, returned_content = NULL, table_format = NULL, include_tabular_header = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`accessions`)) {
        stop("Missing required parameter `accessions`.")
      }












      # explore
      for (query_item in `taxons`) {
        query_params[["taxons"]] <- c(query_params[["taxons"]], list(`taxons` = query_item))
      }

      # explore
      for (query_item in `organelle_types`) {
        query_params[["organelle_types"]] <- c(query_params[["organelle_types"]], list(`organelle_types` = query_item))
      }

      query_params[["first_release_date"]] <- `first_release_date`

      query_params[["last_release_date"]] <- `last_release_date`

      query_params[["tax_exact_match"]] <- `tax_exact_match`

      query_params[["sort.field"]] <- `sort_field`

      query_params[["sort.direction"]] <- `sort_direction`

      query_params[["returned_content"]] <- `returned_content`

      query_params[["table_format"]] <- `table_format`

      query_params[["include_tabular_header"]] <- `include_tabular_header`

      local_var_url_path <- "/organelle/accessions/{accessions}/dataset_report"
      if (!missing(`accessions`)) {
        local_var_url_path <- gsub("\\{accessions\\}", paste(URLencode(as.character(`accessions`), reserved = TRUE), collapse= ",", sep=""), local_var_url_path)
      }

      # API key authentication
      if ("api-key" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["api-key"]) > 0) {
        header_params["api-key"] <- paste(unlist(self$api_client$api_keys["api-key"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("text/plain", "application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "V2reportsOrganelleDataReports"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Get Organelle dataset report by http post
    #'
    #' @param v2_organelle_metadata_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return V2reportsOrganelleDataReports
    OrganelleDatareportByPost = function(v2_organelle_metadata_request, data_file = NULL, ...) {
      local_var_response <- self$OrganelleDatareportByPostWithHttpInfo(v2_organelle_metadata_request, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Get Organelle dataset report by http post
    #'
    #' @param v2_organelle_metadata_request 
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (V2reportsOrganelleDataReports) with additional information such as HTTP status code, headers
    OrganelleDatareportByPostWithHttpInfo = function(v2_organelle_metadata_request, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`v2_organelle_metadata_request`)) {
        stop("Missing required parameter `v2_organelle_metadata_request`.")
      }


      if (!is.null(`v2_organelle_metadata_request`)) {
        local_var_body <- `v2_organelle_metadata_request`$toJSONString()
      } else {
        local_var_body <- NULL
      }

      local_var_url_path <- "/organelle/dataset_report"
      # API key authentication
      if ("api-key" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["api-key"]) > 0) {
        header_params["api-key"] <- paste(unlist(self$api_client$api_keys["api-key"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("text/plain", "application/json")

      # The Content-Type representation header
      local_var_content_types <- list("application/json")

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "POST",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "V2reportsOrganelleDataReports"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    },

    #' @description
    #' Get Organelle dataset report by taxons
    #'
    #' @param taxons NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank
    #' @param organelle_types (optional) No description
    #' @param first_release_date (optional) Only return organelle assemblies that were released on or after the specified date By default, do not filter.
    #' @param last_release_date (optional) Only return organelle assemblies that were released on or before to the specified date By default, do not filter.
    #' @param tax_exact_match (optional) If true, only return assemblies with the given NCBI Taxonomy ID, or name. Otherwise, assemblies from taxonomy subtree are included, too. (default value: FALSE)
    #' @param sort_field (optional) No description
    #' @param sort_direction (optional) No description
    #' @param returned_content (optional) Return either assembly accessions, or entire assembly-metadata records
    #' @param page_size (optional) The maximum number of organelle assemblies to return. Default is 20 and maximum is 1000. If the number of results exceeds the page size, `page_token` can be used to retrieve the remaining results.
    #' @param page_token (optional) A page token is returned from an `OrganelleMetadata` call with more than `page_size` results. Use this token, along with the previous `OrganelleMetadata` parameters, to retrieve the next page of results. When `page_token` is empty, all results have been retrieved.
    #' @param table_format (optional) Optional pre-defined template for processing a tabular data request
    #' @param include_tabular_header (optional) Whether this request for tabular data should include the header row
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return V2reportsOrganelleDataReports
    OrganelleDatareportByTaxon = function(taxons, organelle_types = NULL, first_release_date = NULL, last_release_date = NULL, tax_exact_match = FALSE, sort_field = NULL, sort_direction = NULL, returned_content = NULL, page_size = NULL, page_token = NULL, table_format = NULL, include_tabular_header = NULL, data_file = NULL, ...) {
      local_var_response <- self$OrganelleDatareportByTaxonWithHttpInfo(taxons, organelle_types, first_release_date, last_release_date, tax_exact_match, sort_field, sort_direction, returned_content, page_size, page_token, table_format, include_tabular_header, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        return(local_var_response$content)
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        return(local_var_response)
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        return(local_var_response)
      }
    },

    #' @description
    #' Get Organelle dataset report by taxons
    #'
    #' @param taxons NCBI Taxonomy ID or name (common or scientific) at any taxonomic rank
    #' @param organelle_types (optional) No description
    #' @param first_release_date (optional) Only return organelle assemblies that were released on or after the specified date By default, do not filter.
    #' @param last_release_date (optional) Only return organelle assemblies that were released on or before to the specified date By default, do not filter.
    #' @param tax_exact_match (optional) If true, only return assemblies with the given NCBI Taxonomy ID, or name. Otherwise, assemblies from taxonomy subtree are included, too. (default value: FALSE)
    #' @param sort_field (optional) No description
    #' @param sort_direction (optional) No description
    #' @param returned_content (optional) Return either assembly accessions, or entire assembly-metadata records
    #' @param page_size (optional) The maximum number of organelle assemblies to return. Default is 20 and maximum is 1000. If the number of results exceeds the page size, `page_token` can be used to retrieve the remaining results.
    #' @param page_token (optional) A page token is returned from an `OrganelleMetadata` call with more than `page_size` results. Use this token, along with the previous `OrganelleMetadata` parameters, to retrieve the next page of results. When `page_token` is empty, all results have been retrieved.
    #' @param table_format (optional) Optional pre-defined template for processing a tabular data request
    #' @param include_tabular_header (optional) Whether this request for tabular data should include the header row
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #'
    #' @return API response (V2reportsOrganelleDataReports) with additional information such as HTTP status code, headers
    OrganelleDatareportByTaxonWithHttpInfo = function(taxons, organelle_types = NULL, first_release_date = NULL, last_release_date = NULL, tax_exact_match = FALSE, sort_field = NULL, sort_direction = NULL, returned_content = NULL, page_size = NULL, page_token = NULL, table_format = NULL, include_tabular_header = NULL, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`taxons`)) {
        stop("Missing required parameter `taxons`.")
      }













      # explore
      for (query_item in `organelle_types`) {
        query_params[["organelle_types"]] <- c(query_params[["organelle_types"]], list(`organelle_types` = query_item))
      }

      query_params[["first_release_date"]] <- `first_release_date`

      query_params[["last_release_date"]] <- `last_release_date`

      query_params[["tax_exact_match"]] <- `tax_exact_match`

      query_params[["sort.field"]] <- `sort_field`

      query_params[["sort.direction"]] <- `sort_direction`

      query_params[["returned_content"]] <- `returned_content`

      query_params[["page_size"]] <- `page_size`

      query_params[["page_token"]] <- `page_token`

      query_params[["table_format"]] <- `table_format`

      query_params[["include_tabular_header"]] <- `include_tabular_header`

      local_var_url_path <- "/organelle/taxon/{taxons}/dataset_report"
      if (!missing(`taxons`)) {
        local_var_url_path <- gsub("\\{taxons\\}", paste(URLencode(as.character(`taxons`), reserved = TRUE), collapse= ",", sep=""), local_var_url_path)
      }

      # API key authentication
      if ("api-key" %in% names(self$api_client$api_keys) && nchar(self$api_client$api_keys["api-key"]) > 0) {
        header_params["api-key"] <- paste(unlist(self$api_client$api_keys["api-key"]), collapse = "")
      }

      # The Accept request HTTP header
      local_var_accepts <- list("text/plain", "application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
          self$api_client$WriteFile(local_var_resp, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$DeserializeResponse(local_var_resp, "V2reportsOrganelleDataReports"),
          error = function(e) {
            stop("Failed to deserialize response")
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        return(local_var_resp)
      } 
      
      local_var_error_msg <- local_var_resp$response_as_text()      
      if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        ApiResponse$new(paste("Server returned ", local_var_resp$status_code, " response status code."), local_var_resp)
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        ApiResponse$new("API client error", local_var_resp)
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        if (is.null(local_var_resp$response) || local_var_resp$response == "") {
          local_var_resp$response <- "API server error"
        }
        return(local_var_resp)
      }
    }
  )
)
